-- Split the PR cache off Workspace into its own 1:1 table.
--
-- Every column moved here is a cache of GitHub state or a cursor into it, so a
-- lossy migration would cost one refresh rather than real data -- but the
-- discovery backoff and the review-comment cursor would replay work, so the
-- backfill below copies all thirteen.
--
-- `prUpdatedAt` becomes `syncedAt`: every caller wrote its own observation time
-- into it, never GitHub's PR `updated_at`.

-- CreateTable
CREATE TABLE "WorkspacePR" (
    "workspaceId" TEXT NOT NULL PRIMARY KEY,
    "url" TEXT,
    "number" INTEGER,
    "state" TEXT NOT NULL DEFAULT 'NONE',
    "reviewState" TEXT,
    "ciStatus" TEXT NOT NULL DEFAULT 'UNKNOWN',
    "syncedAt" DATETIME,
    "discoveryLastCheckedAt" DATETIME,
    "discoveryRetryCount" INTEGER NOT NULL DEFAULT 0,
    "discoveryNextCheckAt" DATETIME,
    "ciFailedAt" DATETIME,
    "ciLastNotifiedAt" DATETIME,
    "reviewLastCheckedAt" DATETIME,
    "reviewLastCommentId" TEXT,
    CONSTRAINT "WorkspacePR_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Backfill one row per existing workspace before the columns go away. Every
-- workspace gets a row, including those with no PR, because PR discovery claims
-- its backoff on this row before any PR exists.
INSERT INTO "WorkspacePR" ("workspaceId", "url", "number", "state", "reviewState", "ciStatus", "syncedAt", "discoveryLastCheckedAt", "discoveryRetryCount", "discoveryNextCheckAt", "ciFailedAt", "ciLastNotifiedAt", "reviewLastCheckedAt", "reviewLastCommentId")
SELECT "id", "prUrl", "prNumber", "prState", "prReviewState", "prCiStatus", "prUpdatedAt", "prDiscoveryLastCheckedAt", "prDiscoveryRetryCount", "prDiscoveryNextCheckAt", "prCiFailedAt", "prCiLastNotifiedAt", "prReviewLastCheckedAt", "prReviewLastCommentId"
FROM "Workspace";

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Workspace" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "worktreePath" TEXT,
    "branchName" TEXT,
    "isAutoGeneratedBranch" BOOLEAN NOT NULL DEFAULT false,
    "creationSource" TEXT NOT NULL DEFAULT 'MANUAL',
    "creationMetadata" JSONB,
    "initErrorMessage" TEXT,
    "initOutput" TEXT,
    "initStartedAt" DATETIME,
    "initCompletedAt" DATETIME,
    "initScriptPid" INTEGER,
    "initRetryCount" INTEGER NOT NULL DEFAULT 0,
    "runScriptCommand" TEXT,
    "runScriptPostRunCommand" TEXT,
    "runScriptCleanupCommand" TEXT,
    "runScriptPid" INTEGER,
    "runScriptPort" INTEGER,
    "runScriptStartedAt" DATETIME,
    "runScriptStatus" TEXT NOT NULL DEFAULT 'IDLE',
    "githubIssueNumber" INTEGER,
    "githubIssueUrl" TEXT,
    "linearIssueId" TEXT,
    "linearIssueIdentifier" TEXT,
    "linearIssueUrl" TEXT,
    "defaultSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "ratchetSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "mode" TEXT NOT NULL DEFAULT 'STANDARD',
    "autoIterationStatus" TEXT,
    "autoIterationConfig" JSONB,
    "autoIterationProgress" JSONB,
    "autoIterationSessionId" TEXT,
    "periodicTaskId" TEXT,
    "parent_workspace_id" TEXT,
    "hasHadSessions" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "Workspace_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Workspace_periodicTaskId_fkey" FOREIGN KEY ("periodicTaskId") REFERENCES "PeriodicTask" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Workspace_parent_workspace_id_fkey" FOREIGN KEY ("parent_workspace_id") REFERENCES "Workspace" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Workspace" ("autoIterationConfig", "autoIterationProgress", "autoIterationSessionId", "autoIterationStatus", "branchName", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initScriptPid", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "mode", "name", "parent_workspace_id", "periodicTaskId", "projectId", "ratchetSessionProvider", "runScriptCleanupCommand", "runScriptCommand", "runScriptPid", "runScriptPort", "runScriptPostRunCommand", "runScriptStartedAt", "runScriptStatus", "status", "updatedAt", "worktreePath") SELECT "autoIterationConfig", "autoIterationProgress", "autoIterationSessionId", "autoIterationStatus", "branchName", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initScriptPid", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "mode", "name", "parent_workspace_id", "periodicTaskId", "projectId", "ratchetSessionProvider", "runScriptCleanupCommand", "runScriptCommand", "runScriptPid", "runScriptPort", "runScriptPostRunCommand", "runScriptStartedAt", "runScriptStatus", "status", "updatedAt", "worktreePath" FROM "Workspace";
DROP TABLE "Workspace";
ALTER TABLE "new_Workspace" RENAME TO "Workspace";
CREATE INDEX "Workspace_projectId_idx" ON "Workspace"("projectId");
CREATE INDEX "Workspace_status_idx" ON "Workspace"("status");
CREATE INDEX "Workspace_parent_workspace_id_idx" ON "Workspace"("parent_workspace_id");
CREATE INDEX "Workspace_projectId_status_idx" ON "Workspace"("projectId", "status");
CREATE INDEX "Workspace_projectId_updatedAt_idx" ON "Workspace"("projectId", "updatedAt");
CREATE INDEX "Workspace_projectId_createdAt_idx" ON "Workspace"("projectId", "createdAt");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE INDEX "WorkspacePR_url_discoveryNextCheckAt_idx" ON "WorkspacePR"("url", "discoveryNextCheckAt");

-- CreateIndex
CREATE INDEX "WorkspacePR_syncedAt_idx" ON "WorkspacePR"("syncedAt");

-- SQLite's RedefineTables above dropped and recreated "Workspace", which drops
-- every trigger attached to it. Recreate the depth-1 guards verbatim; any future
-- migration that redefines this table has to do the same.
CREATE TRIGGER enforce_workspace_depth_1
BEFORE INSERT ON "Workspace"
WHEN NEW."parent_workspace_id" IS NOT NULL
BEGIN
  -- Block self-parenting
  SELECT RAISE(ABORT, 'A workspace cannot be its own parent')
  WHERE NEW."id" = NEW."parent_workspace_id";
  -- Block grandchild chains: proposed parent must not already have a parent
  SELECT RAISE(ABORT, 'Child workspaces cannot have children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "id" = NEW."parent_workspace_id"
    AND "parent_workspace_id" IS NOT NULL
  );
END;

CREATE TRIGGER enforce_workspace_depth_1_update
BEFORE UPDATE ON "Workspace"
WHEN NEW."parent_workspace_id" IS NOT NULL
BEGIN
  -- Block self-parenting
  SELECT RAISE(ABORT, 'A workspace cannot be its own parent')
  WHERE NEW."id" = NEW."parent_workspace_id";
  -- Block grandchild chains: proposed parent must not already have a parent
  SELECT RAISE(ABORT, 'Child workspaces cannot have children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "id" = NEW."parent_workspace_id"
    AND "parent_workspace_id" IS NOT NULL
  );
  -- Block re-parenting a workspace that already has children
  SELECT RAISE(ABORT, 'Cannot re-parent a workspace that already has children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "parent_workspace_id" = NEW."id"
  );
END;
