import type { Prisma, Workspace, WorkspaceAutoIteration } from '@prisma-gen/client';
import { prisma } from '@/backend/db';
import {
  flattenWorkspaceAutoIteration,
  type WorkspaceAutoIterationFields,
  workspaceAutoIterationAccessor,
} from '@/backend/services/workspace/resources/workspace-auto-iteration.accessor';
import {
  flattenWorkspacePR,
  type PRAggregateGuard,
  type WorkspacePRFields,
  type WorkspacePRRow,
  type WorkspacePRWriteFields,
  workspacePrAccessor,
} from '@/backend/services/workspace/resources/workspace-pr.accessor';
import {
  flattenWorkspaceRatchet,
  type WorkspaceRatchetFields,
  type WorkspaceRatchetRow,
  workspaceRatchetAccessor,
} from '@/backend/services/workspace/resources/workspace-ratchet.accessor';
import {
  flattenWorkspaceRunScript,
  type RunScriptCommandFields,
  type RunScriptExecutionFields,
  type RunScriptExecutionUpdate,
  type WorkspaceRunScriptFields,
  type WorkspaceRunScriptRow,
  workspaceRunScriptAccessor,
} from '@/backend/services/workspace/resources/workspace-run-script.accessor';
import type {
  WorkspaceFixerContext,
  WorkspacePRContext,
  WorkspaceProviderSelectionSnapshot,
  WorkspaceStatusSnapshot,
} from '@/backend/services/workspace/types';
import {
  type AutoIterationStatus,
  type CIStatus,
  deriveRatchetState,
  type PRState,
  type RatchetState,
  type RunScriptStatus,
  type WorkspaceMode,
  type WorkspaceStatus,
} from '@/shared/core';

/**
 * Spans both tables now: the worktree path is the workspace's, the session id is
 * the loop's. Declared explicitly rather than via `WorkspaceGetPayload` because
 * the payload shape no longer matches the flat one callers consume.
 */
const autoIterationExecutionContextSelect = {
  worktreePath: true,
  autoIteration: { select: { sessionId: true } },
} satisfies Prisma.WorkspaceSelect;

export interface AutoIterationExecutionContext {
  worktreePath: string | null;
  autoIterationSessionId: string | null;
}

/**
 * The four process columns, under the flat names they had on `Workspace`. Now a
 * `WorkspaceRunScript` read; the shape is unchanged because the run-script state
 * machine passes it around.
 */
export type RunScriptExecutionState = RunScriptExecutionFields;

/**
 * Threshold for considering a PROVISIONING workspace as stale.
 * Workspaces in PROVISIONING state for longer than this are considered
 * stuck (e.g., due to server crash) and will be recovered by reconciliation.
 */
const STALE_PROVISIONING_THRESHOLD_MS = 10 * 60 * 1000; // 10 minutes

/**
 * Threshold for considering an ARCHIVING workspace as stale.
 * ARCHIVING is a persisted transient state; after this threshold, no
 * in-flight archive from the current process should still be active.
 */
const STALE_ARCHIVING_THRESHOLD_MS = 10 * 60 * 1000; // 10 minutes

interface CreateWorkspaceInput {
  projectId: string;
  name: string;
  description?: string;
  branchName?: string;
  githubIssueNumber?: number;
  githubIssueUrl?: string;
  linearIssueId?: string;
  linearIssueIdentifier?: string;
  linearIssueUrl?: string;
  isAutoGeneratedBranch?: boolean;
  ratchetEnabled?: boolean;
  defaultSessionProvider?: Prisma.WorkspaceCreateInput['defaultSessionProvider'];
  ratchetSessionProvider?: Prisma.WorkspaceCreateInput['ratchetSessionProvider'];
  creationSource?:
    | 'MANUAL'
    | 'RESUME_BRANCH'
    | 'GITHUB_ISSUE'
    | 'LINEAR_ISSUE'
    | 'PERIODIC_TASK'
    | 'CHILD_WORKSPACE';
  creationMetadata?: Prisma.InputJsonValue;
  mode?: 'STANDARD' | 'AUTO_ITERATION';
  autoIterationConfig?: Prisma.InputJsonValue;
  periodicTaskId?: string;
  parentWorkspaceId?: string;
}

interface UpdateWorkspaceInput {
  name?: string;
  description?: string;
  // Note: status changes must go through workspaceStateMachine, not direct updates
  worktreePath?: string | null;
  branchName?: string | null;
  isAutoGeneratedBranch?: boolean;
  githubIssueNumber?: number | null;
  githubIssueUrl?: string | null;
  // The PR cache lives on WorkspacePR; see workspacePrAccessor.
  // Ratchet state lives on WorkspaceRatchet; see workspaceRatchetAccessor.
  defaultSessionProvider?: Prisma.WorkspaceUpdateInput['defaultSessionProvider'];
  ratchetSessionProvider?: Prisma.WorkspaceUpdateInput['ratchetSessionProvider'];
  // Activity tracking
  hasHadSessions?: boolean;
  // The run-script group lives on WorkspaceRunScript; see workspaceRunScriptAccessor.
  // The auto-iteration group lives on WorkspaceAutoIteration; see
  // workspaceAutoIterationAccessor.
}

export interface PrSnapshotPersistenceInput {
  prUrl?: string | null;
  prNumber: number;
  prState: PRState;
  prReviewState: string | null;
  prCiStatus: CIStatus;
  prUpdatedAt: Date;
  branchName?: string;
}

/**
 * One ratchet check's observation. Every field is an input to
 * `deriveRatchetState`, which is why this is no longer CI-only: the projection
 * reads the cache, so the check has to write what it saw.
 */
export interface PrObservationPersistenceInput {
  /**
   * The PR this observation was fetched for. Guarded, never written: the ratchet
   * does not attach PRs, it reports on the one already attached.
   *
   * The aggregate compare-and-swap cannot cover this on its own, because it reads
   * its guard inside the write transaction — it catches a write racing the
   * transaction, not a workspace re-pointed at a new PR while the check was off
   * fetching. Without this, a check that observed `MERGED` on the old PR could
   * stamp it onto the new one, and a workspace deriving `MERGED` leaves the ratchet
   * poll set altogether.
   */
  expectedPrUrl: string;
  expectedPrNumber: number;
  prCiStatus: CIStatus;
  prState: PRState;
  prReviewState: string | null;
  prHasMergeConflict: boolean;
  prUpdatedAt: Date;
  prCiFailedAt?: Date | null;
}

export interface PrAggregatePersistenceResult {
  applied: boolean;
  dispatchReset: boolean;
}

interface PrObservationIdentityGuard {
  prUrl: string;
  prNumber: number;
}

type PrAggregatePersistenceInput = Partial<{
  prUrl: string | null;
  prNumber: number | null;
  prState: PRState;
  prReviewState: string | null;
  prCiStatus: CIStatus;
  prHasMergeConflict: boolean;
  prCiFailedAt: Date | null;
  branchName: string | null;
}> & { prUpdatedAt: Date };

interface FindByProjectIdFilters {
  excludeStatuses?: WorkspaceStatus[];
}

/**
 * Whether an observation moves the PR aggregate, which is what makes a settled
 * ratchet dispatch stale.
 *
 * A field the observation omits cannot have changed, so it is skipped rather
 * than compared against `undefined`. `prUpdatedAt` is deliberately not here: it
 * moves on every refresh, and counting it would reset the dispatch every time
 * the poller ran.
 */
function prAggregateChanged(
  current: PRAggregateGuard,
  observation: PrAggregatePersistenceInput
): boolean {
  const compared: Array<keyof PRAggregateGuard> = [
    'prUrl',
    'prNumber',
    'prState',
    'prReviewState',
    'prCiStatus',
    // A conflict appearing or clearing changes the PR state a fixer was
    // dispatched for, so it invalidates a settled dispatch like any other
    // aggregate field. It joins the guard as well as the comparison, so the two
    // writers of this column cannot race each other.
    'prHasMergeConflict',
  ];
  return compared.some(
    (field) => observation[field] !== undefined && current[field] !== observation[field]
  );
}

function prIdentityChanged(
  current: PRAggregateGuard,
  expected?: PrObservationIdentityGuard
): boolean {
  if (!expected) {
    return false;
  }
  if (current.prNumber !== null && current.prNumber !== expected.prNumber) {
    return true;
  }
  return current.prUrl !== expected.prUrl;
}

/**
 * All four split groups — the ratchet, the PR cache, the run script and
 * auto-iteration — live in their own tables
 * now, but the reads that feed derived state and the snapshot stream consumed
 * them as flat `ratchet*`, `pr*` and `runScript*` fields on the workspace.
 * `flatten` keeps that shape, so all three splits stop at this accessor instead
 * of rippling out through derived state, the snapshot wire and the client.
 *
 * `ratchetState` is in that shape too, but it is no longer read from a column: it
 * is projected here from the PR fields joined in alongside it. Computing it at the
 * same boundary that flattens is what keeps a stored copy from existing to
 * disagree with them — and what let the projection land without touching any of
 * the forty files that read `workspace.ratchetState`.
 */
type Flattened<T> = Omit<T, 'ratchet' | 'pr' | 'runScript' | 'autoIteration'> &
  WorkspaceRatchetFields &
  WorkspacePRFields &
  WorkspaceRunScriptFields &
  WorkspaceAutoIterationFields & { ratchetState: RatchetState };

function flatten<
  T extends {
    ratchet?: WorkspaceRatchetRow | null;
    pr?: WorkspacePRRow | null;
    runScript?: WorkspaceRunScriptRow | null;
    autoIteration?: WorkspaceAutoIteration | null;
  },
>(row: T): Flattened<T> {
  const { ratchet, pr, runScript, autoIteration, ...rest } = row;
  const ratchetFields = flattenWorkspaceRatchet(ratchet);
  const prFields = flattenWorkspacePR(pr);
  return {
    ...rest,
    ...ratchetFields,
    ...prFields,
    ...flattenWorkspaceRunScript(runScript),
    ...flattenWorkspaceAutoIteration(autoIteration),
    ratchetState: deriveRatchetState({
      ratchetEnabled: ratchetFields.ratchetEnabled,
      prState: prFields.prState,
      prCiStatus: prFields.prCiStatus,
      prHasMergeConflict: prFields.prHasMergeConflict,
      prReviewState: prFields.prReviewState,
    }),
  };
}

/** Included on every read that has to reproduce the old flat workspace shape. */
const sideTables = {
  ratchet: true,
  pr: true,
  runScript: true,
  autoIteration: true,
} satisfies Prisma.WorkspaceInclude;

type SideTableInclude = { ratchet: true; pr: true; runScript: true; autoIteration: true };

/** A bare workspace row with its side-table fields flattened on. */
export type WorkspaceWithRatchet = Flattened<
  Prisma.WorkspaceGetPayload<{ include: SideTableInclude }>
>;

type WorkspaceWithAgentSessions = Flattened<
  Prisma.WorkspaceGetPayload<{
    include: { agentSessions: true; terminalSessions: true } & SideTableInclude;
  }>
>;

export type WorkspaceWithSessions = WorkspaceWithAgentSessions;

/**
 * Workspace with project included, PR cache flattened on.
 *
 * The PR fields are here because callers of these finders read them — archive
 * decides whether to comment on the linked issue from `prState`/`prUrl`. The
 * ratchet fields are not, because none of them do.
 */
/**
 * A narrower read than the full flatten: this one joins only what its callers
 * use. `autoIteration` is here because workspace init branches on `mode` to
 * decide whether to start a default session or leave the loop to manage its own.
 */
type WorkspaceWithProjectInclude = { project: true; pr: true; autoIteration: true };

type WorkspaceWithProject = Omit<
  Prisma.WorkspaceGetPayload<{ include: WorkspaceWithProjectInclude }>,
  'pr' | 'autoIteration'
> &
  WorkspacePRFields &
  WorkspaceAutoIterationFields;

function withProjectAndPR(
  row: Prisma.WorkspaceGetPayload<{ include: WorkspaceWithProjectInclude }>
): WorkspaceWithProject {
  const { pr, autoIteration, ...rest } = row;
  return { ...rest, ...flattenWorkspacePR(pr), ...flattenWorkspaceAutoIteration(autoIteration) };
}

type WorkspaceWithAgentSessionsAndProject = Flattened<
  Prisma.WorkspaceGetPayload<{
    include: {
      agentSessions: true;
      terminalSessions: true;
      project: true;
    } & SideTableInclude;
  }>
>;

// Type for Workspace with sessions and project included (used by reconciliation)
export type WorkspaceWithSessionsAndProject = WorkspaceWithAgentSessionsAndProject;

class WorkspaceAccessor {
  async create(data: CreateWorkspaceInput): Promise<WorkspaceWithRatchet> {
    const created = await prisma.workspace.create({
      data: {
        projectId: data.projectId,
        name: data.name,
        description: data.description,
        branchName: data.branchName,
        githubIssueNumber: data.githubIssueNumber,
        githubIssueUrl: data.githubIssueUrl,
        linearIssueId: data.linearIssueId,
        linearIssueIdentifier: data.linearIssueIdentifier,
        linearIssueUrl: data.linearIssueUrl,
        isAutoGeneratedBranch: data.isAutoGeneratedBranch ?? false,
        // Every workspace gets all four side-table rows here, so no later code
        // path can create a workspace that their row-guarded writes would skip. PR
        // discovery in particular claims its backoff before any PR exists, the
        // run-script status compare-and-swap needs a row before the first start,
        // and the auto-iteration session guards need one before the first loop.
        ratchet: { create: { enabled: data.ratchetEnabled } },
        pr: { create: {} },
        runScript: { create: {} },
        // `mode` and `config` are the two auto-iteration columns known at
        // creation; the loop's own three are written by its accessor later.
        autoIteration: { create: { mode: data.mode, config: data.autoIterationConfig } },
        defaultSessionProvider: data.defaultSessionProvider,
        ratchetSessionProvider: data.ratchetSessionProvider,
        creationSource: data.creationSource,
        creationMetadata: data.creationMetadata,
        periodicTaskId: data.periodicTaskId,
        parentWorkspaceId: data.parentWorkspaceId,
      },
      include: sideTables,
    });
    return flatten(created);
  }

  async findById(id: string): Promise<WorkspaceWithSessions | null> {
    const row = await prisma.workspace.findUnique({
      where: { id },
      include: {
        agentSessions: true,
        terminalSessions: true,
        ...sideTables,
      },
    });
    return row ? flatten(row) : null;
  }

  /**
   * Find a workspace without relation includes.
   * Used by state machines that only need the raw row.
   */
  findRawById(id: string): Promise<Workspace | null> {
    return prisma.workspace.findUnique({
      where: { id },
    });
  }

  async exists(id: string): Promise<boolean> {
    const workspace = await prisma.workspace.findUnique({
      where: { id },
      select: { id: true },
    });
    return workspace !== null;
  }

  findProviderSelection(id: string): Promise<WorkspaceProviderSelectionSnapshot | null> {
    return prisma.workspace.findUnique({
      where: { id },
      select: {
        id: true,
        defaultSessionProvider: true,
        ratchetSessionProvider: true,
      },
    });
  }

  findFixerContext(id: string): Promise<WorkspaceFixerContext | null> {
    return prisma.workspace.findUnique({
      where: { id },
      select: {
        id: true,
        worktreePath: true,
        defaultSessionProvider: true,
        ratchetSessionProvider: true,
      },
    });
  }

  async findStatusSnapshot(id: string): Promise<WorkspaceStatusSnapshot | null> {
    const row = await prisma.workspace.findUnique({
      where: { id },
      select: {
        status: true,
        initCompletedAt: true,
        pr: { select: { url: true, number: true } },
      },
    });
    if (!row) {
      return null;
    }
    return {
      status: row.status,
      initCompletedAt: row.initCompletedAt,
      prUrl: row.pr?.url ?? null,
      prNumber: row.pr?.number ?? null,
    };
  }

  async findPRContext(id: string): Promise<WorkspacePRContext | null> {
    const row = await prisma.workspace.findUnique({
      where: { id },
      select: { branchName: true, pr: { select: { url: true } } },
    });
    return row ? { branchName: row.branchName, prUrl: row.pr?.url ?? null } : null;
  }

  /**
   * Find a workspace without relation includes and throw if missing.
   * Used by state machines after compare-and-swap updates.
   */
  findRawByIdOrThrow(id: string): Promise<Workspace> {
    return prisma.workspace.findUniqueOrThrow({
      where: { id },
    });
  }

  async findAutoIterationExecutionContext(
    id: string
  ): Promise<AutoIterationExecutionContext | null> {
    const workspace = await prisma.workspace.findUnique({
      where: { id },
      select: autoIterationExecutionContextSelect,
    });
    if (!workspace) {
      return null;
    }
    return {
      worktreePath: workspace.worktreePath,
      autoIterationSessionId: workspace.autoIteration?.sessionId ?? null,
    };
  }

  findRunScriptExecutionState(id: string): Promise<RunScriptExecutionState | null> {
    return workspaceRunScriptAccessor.findExecutionState(id);
  }

  findRunScriptExecutionStateOrThrow(id: string): Promise<RunScriptExecutionState> {
    return workspaceRunScriptAccessor.findExecutionStateOrThrow(id);
  }

  findByProjectId(projectId: string): Promise<Workspace[]> {
    return prisma.workspace.findMany({
      where: { projectId },
      orderBy: { updatedAt: 'desc' },
    });
  }

  /** Find workspaces with sessions included, for derived-state computation. */
  async findByProjectIdWithSessions(
    projectId: string,
    filters?: FindByProjectIdFilters
  ): Promise<WorkspaceWithSessions[]> {
    const where: Prisma.WorkspaceWhereInput = { projectId };

    if (filters?.excludeStatuses && filters.excludeStatuses.length > 0) {
      where.status = { notIn: filters.excludeStatuses };
    }

    const rows = await prisma.workspace.findMany({
      where,
      orderBy: { updatedAt: 'desc' },
      include: {
        agentSessions: true,
        terminalSessions: true,
        ...sideTables,
      },
    });
    return rows.map(flatten);
  }

  /**
   * Find all non-archived workspaces with sessions and project included.
   * Used by the reconciliation service for single-query fetch of all workspace data.
   */
  async findAllNonArchivedWithSessionsAndProject(): Promise<WorkspaceWithSessionsAndProject[]> {
    const rows = await prisma.workspace.findMany({
      where: { status: { not: 'ARCHIVED' } },
      include: {
        agentSessions: true,
        terminalSessions: true,
        project: true,
        ...sideTables,
      },
      orderBy: { updatedAt: 'desc' },
    });
    return rows.map(flatten);
  }

  update(id: string, data: UpdateWorkspaceInput): Promise<Workspace> {
    return prisma.workspace.update({
      where: { id },
      data,
    });
  }

  /**
   * Atomic compare-and-swap transition for workspace status.
   * Returns count=1 only when current status matches fromStatus.
   * Used to prevent race conditions in state transitions.
   */
  transitionWithCas(
    id: string,
    fromStatus: WorkspaceStatus,
    data: Prisma.WorkspaceUpdateManyMutationInput
  ): Promise<{ count: number }> {
    return prisma.workspace.updateMany({
      where: { id, status: fromStatus },
      data,
    });
  }

  /**
   * Compare-and-swap update for run script status transitions.
   * Returns count=1 only when current status matches.
   */
  casRunScriptStatusUpdate(
    id: string,
    currentStatus: RunScriptStatus,
    data: RunScriptExecutionUpdate
  ): Promise<{ count: number }> {
    return workspaceRunScriptAccessor.casExecutionUpdate(id, currentStatus, data);
  }

  /**
   * Write the cached `factory-factory.json` commands alongside the worktree the
   * config was read from.
   *
   * The worktree columns are the workspace's own and the commands are the
   * run-script row's, so this is the transaction that keeps a freshly initialized
   * worktree from being observable without the commands it declared — one
   * statement before the split.
   */
  async registerInitializedWorktree(
    id: string,
    worktree: { worktreePath: string; branchName: string | null; isAutoGeneratedBranch: boolean },
    commands: RunScriptCommandFields
  ): Promise<void> {
    await prisma.$transaction(async (transaction) => {
      await transaction.workspace.update({ where: { id }, data: worktree });
      await workspaceRunScriptAccessor.writeCommands(id, commands, transaction);
    });
  }

  /** Refresh the cached commands from the worktree's `factory-factory.json`. */
  setRunScriptCommands(id: string, commands: RunScriptCommandFields): Promise<void> {
    return workspaceRunScriptAccessor.writeCommands(id, commands);
  }

  setAutoIterationStatus(
    id: string,
    status: AutoIterationStatus
  ): Promise<{ mode: WorkspaceMode; status: AutoIterationStatus }> {
    return workspaceAutoIterationAccessor.setStatus(id, status);
  }

  setAutoIterationProgress(id: string, progress: Prisma.InputJsonValue): Promise<void> {
    return workspaceAutoIterationAccessor.setProgress(id, progress);
  }

  setAutoIterationSessionId(id: string, sessionId: string | null): Promise<void> {
    return workspaceAutoIterationAccessor.setSession(id, sessionId);
  }

  finishAutoIterationIfSessionMatches(
    id: string,
    sessionId: string,
    status: AutoIterationStatus
  ): Promise<{ settled: boolean; mode: WorkspaceMode | null }> {
    return workspaceAutoIterationAccessor.finishIfSessionMatches(id, sessionId, status);
  }

  clearAutoIterationSessionIfMatches(id: string, sessionId: string): Promise<boolean> {
    return workspaceAutoIterationAccessor.clearSessionIfMatches(id, sessionId);
  }

  /**
   * Reset auto-iteration loops left RUNNING by a crash or restart. Called at
   * server startup; see the accessor for why FAILED rather than PAUSED.
   */
  resetStaleAutoIterationStatuses(): Promise<Array<{ id: string }>> {
    return workspaceAutoIterationAccessor.resetStaleRunningStatuses();
  }

  /**
   * Find workspaces with transient run script statuses (STARTING or STOPPING)
   * and reset them to IDLE. Called at server startup to recover states left
   * in-flight by a server crash or restart.
   * Returns the affected workspaces (id + prior status) for logging/event emission.
   */
  resetStaleRunScriptStatuses(): Promise<Array<{ id: string; runScriptStatus: RunScriptStatus }>> {
    return workspaceRunScriptAccessor.resetStaleTransientStatuses();
  }

  /**
   * Conditional provisioning retry transition (FAILED -> PROVISIONING).
   * Returns count=1 when retry is allowed and transition was applied.
   */
  startProvisioningRetryIfAllowed(id: string, maxRetries: number): Promise<{ count: number }> {
    return prisma.workspace.updateMany({
      where: {
        id,
        status: 'FAILED',
        initRetryCount: { lt: maxRetries },
      },
      data: {
        status: 'PROVISIONING',
        initRetryCount: { increment: 1 },
        initStartedAt: new Date(),
        initErrorMessage: null,
        initScriptPid: null,
      },
    });
  }

  /**
   * Conditional provisioning retry transition (READY -> PROVISIONING).
   * Used when a workspace is READY+warning and the user retries the setup script.
   * Returns count=1 when retry is allowed and transition was applied.
   */
  startProvisioningFromReadyIfAllowed(id: string, maxRetries: number): Promise<{ count: number }> {
    return prisma.workspace.updateMany({
      where: {
        id,
        status: 'READY',
        initRetryCount: { lt: maxRetries },
      },
      data: {
        status: 'PROVISIONING',
        initRetryCount: { increment: 1 },
        initStartedAt: new Date(),
        initErrorMessage: null,
        initScriptPid: null,
      },
    });
  }

  /**
   * Conditional reset transition (FAILED -> NEW).
   * Returns count=1 when retry is allowed and transition was applied.
   */
  resetToNewIfAllowed(id: string, maxRetries: number): Promise<{ count: number }> {
    return prisma.workspace.updateMany({
      where: {
        id,
        status: 'FAILED',
        initRetryCount: { lt: maxRetries },
      },
      data: {
        status: 'NEW',
        initRetryCount: { increment: 1 },
        initStartedAt: null,
        initCompletedAt: null,
        initErrorMessage: null,
        initScriptPid: null,
      },
    });
  }

  delete(id: string): Promise<Workspace> {
    return prisma.workspace.delete({
      where: { id },
    });
  }

  // Note: archive functionality is provided by workspaceStateMachine.archive()

  /**
   * Find workspaces that need worktree creation or recovery.
   * Returns:
   * - NEW workspaces that haven't started provisioning yet
   * - PROVISIONING workspaces that are stale (>10 minutes) and likely stuck due to server crash
   *
   * Used for reconciliation to ensure all workspaces are initialized.
   * Includes project for worktree creation.
   */
  async findNeedingWorktree(): Promise<WorkspaceWithProject[]> {
    const staleThreshold = new Date(Date.now() - STALE_PROVISIONING_THRESHOLD_MS);

    const rows = await prisma.workspace.findMany({
      where: {
        OR: [
          { status: 'NEW' },
          {
            status: 'PROVISIONING',
            initStartedAt: { lt: staleThreshold },
          },
        ],
      },
      include: { project: true, pr: true, autoIteration: true },
      orderBy: { createdAt: 'asc' },
    });
    return rows.map(withProjectAndPR);
  }

  /**
   * Find ARCHIVING workspaces that have been stuck long enough to recover.
   * Includes project data so the archive workflow can safely clean up worktrees.
   */
  async findStaleArchivingWithProject(): Promise<WorkspaceWithProject[]> {
    const staleThreshold = new Date(Date.now() - STALE_ARCHIVING_THRESHOLD_MS);

    const rows = await prisma.workspace.findMany({
      where: {
        status: 'ARCHIVING',
        updatedAt: { lt: staleThreshold },
      },
      include: { project: true, pr: true, autoIteration: true },
      orderBy: { updatedAt: 'asc' },
    });
    return rows.map(withProjectAndPR);
  }

  /**
   * Find workspace by ID with project included.
   * Used when project info is needed (e.g., for worktree creation).
   */
  async findByIdWithProject(id: string): Promise<WorkspaceWithProject | null> {
    const row = await prisma.workspace.findUnique({
      where: { id },
      include: { project: true, pr: true, autoIteration: true },
    });
    return row ? withProjectAndPR(row) : null;
  }

  /**
   * PR sync and PR discovery candidates moved to `workspacePrAccessor`
   * (`findNeedingSync` / `findNeedingDiscovery`) along with the columns they
   * filter and order on.
   */

  /**
   * Mark workspace as having had sessions (for kanban backlog/waiting distinction).
   * Uses atomic conditional update to prevent race conditions when multiple sessions start.
   */
  async markHasHadSessions(id: string): Promise<void> {
    await prisma.workspace.updateMany({
      where: { id, hasHadSessions: false },
      data: { hasHadSessions: true },
    });
  }

  /**
   * Persist a PR aggregate and clear ownership from a settled dispatch when the
   * newly fetched aggregate changed.
   *
   * Both writes happen in one transaction, each guarded by the state it was
   * decided from: the aggregate against the aggregate the caller read, the
   * reset against the dispatch metadata read alongside it. If a newer dispatch
   * wins that race the aggregate is still written and the dispatch keeps its
   * claim. Identical periodic refreshes leave settled metadata untouched, and a
   * RUNNING dispatch is never eligible for the reset.
   */
  applyPrSnapshotWithDispatchReset(
    workspaceId: string,
    observation: PrSnapshotPersistenceInput
  ): Promise<PrAggregatePersistenceResult> {
    return this.applyPrAggregateUpdateWithDispatchReset(workspaceId, observation);
  }

  applyPrObservationWithDispatchReset(
    workspaceId: string,
    observation: PrObservationPersistenceInput
  ): Promise<PrAggregatePersistenceResult> {
    const { expectedPrUrl, expectedPrNumber, ...fields } = observation;
    return this.applyPrAggregateUpdateWithDispatchReset(workspaceId, fields, {
      prUrl: expectedPrUrl,
      prNumber: expectedPrNumber,
    });
  }

  /**
   * Write a PR observation together with a corrected branch name.
   *
   * A refresh discovers the two at once — the PR's head branch can differ from
   * what the workspace recorded — and they now live in different tables, so this
   * is the transaction that keeps them from being observable apart.
   */
  async recordPrSnapshotWithBranchName(
    workspaceId: string,
    branchName: string | null,
    prFields: WorkspacePRWriteFields
  ): Promise<void> {
    await prisma.$transaction(async (transaction) => {
      await workspacePrAccessor.writeInTransaction(transaction, workspaceId, prFields);
      await transaction.workspace.update({ where: { id: workspaceId }, data: { branchName } });
    });
  }

  /**
   * Rename the branch and clear the PR discovery schedule together, so discovery
   * re-checks the new branch immediately instead of waiting out a backoff earned
   * by the old one.
   */
  async setBranchNameAndClearDiscoverySchedule(
    workspaceId: string,
    branchName: string
  ): Promise<void> {
    await prisma.$transaction(async (transaction) => {
      await transaction.workspace.update({
        where: { id: workspaceId },
        data: { branchName, isAutoGeneratedBranch: false },
      });
      await workspacePrAccessor.clearDiscoverySchedule(transaction, workspaceId);
    });
  }

  private async applyPrAggregateUpdateWithDispatchReset(
    workspaceId: string,
    observation: PrAggregatePersistenceInput,
    /** The exact PR identity the observation was fetched from. */
    expectedPr?: PrObservationIdentityGuard
  ): Promise<PrAggregatePersistenceResult> {
    const { branchName, ...prFields } = observation;
    return await prisma.$transaction(async (transaction) => {
      const current = await workspacePrAccessor.readAggregate(transaction, workspaceId);
      if (!current) {
        return { applied: false, dispatchReset: false };
      }
      if (prIdentityChanged(current, expectedPr)) {
        return { applied: false, dispatchReset: false };
      }
      const dispatch = await workspaceRatchetAccessor.readDispatchGuard(transaction, workspaceId);
      const shouldReset =
        prAggregateChanged(current, observation) &&
        (dispatch?.dispatchOutcome === 'COMPLETED' || dispatch?.dispatchOutcome === 'DIED');

      const applied = await workspacePrAccessor.applyAggregateIfUnchanged(
        transaction,
        workspaceId,
        current,
        prFields
      );
      if (!applied) {
        return { applied: false, dispatchReset: false };
      }

      // The corrected branch name is the workspace's own column, so it lands as
      // a second statement in the same transaction — only once the aggregate
      // write it was observed alongside has held.
      if (branchName !== undefined) {
        await transaction.workspace.update({ where: { id: workspaceId }, data: { branchName } });
      }

      // Only once the aggregate write has landed, and only for a dispatch that
      // has not moved on since it was read.
      const dispatchReset =
        shouldReset && dispatch
          ? await workspaceRatchetAccessor.resetSettledDispatch(transaction, workspaceId, dispatch)
          : false;
      return { applied: true, dispatchReset };
    });
  }

  /**
   * Append output to initOutput field during startup script execution.
   * Truncates from the beginning if output exceeds maxSize to prevent unbounded growth.
   */
  async appendInitOutput(id: string, output: string, maxSize = 50 * 1024): Promise<void> {
    const truncationMarker = '[...truncated...]\n';
    const markerLength = truncationMarker.length;
    const now = new Date();
    const updatedRows = await prisma.$executeRaw`
      UPDATE "Workspace"
      SET "initOutput" = CASE
        WHEN length(COALESCE("initOutput", '') || ${output}) <= ${maxSize}
          THEN COALESCE("initOutput", '') || ${output}
        WHEN ${maxSize} <= ${markerLength}
          THEN substr(${truncationMarker}, 1, ${maxSize})
        ELSE ${truncationMarker} || substr(
          COALESCE("initOutput", '') || ${output},
          -(${maxSize} - ${markerLength})
        )
      END,
      "updatedAt" = ${now}
      WHERE "id" = ${id}
    `;

    if (Number(updatedRows) === 0) {
      const existing = await prisma.workspace.findUnique({
        where: { id },
        select: { id: true },
      });
      if (!existing) {
        throw new Error(`Workspace not found: ${id}`);
      }
    }
  }

  /**
   * Track the currently running startup/setup script process for provisioning recovery.
   */
  async setInitScriptPid(id: string, pid: number): Promise<void> {
    await prisma.workspace.updateMany({
      where: { id, status: 'PROVISIONING' },
      data: { initScriptPid: pid },
    });
  }

  /**
   * Clear startup/setup script process tracking if it still points to the given process.
   */
  async clearInitScriptPid(id: string, pid: number): Promise<void> {
    await prisma.workspace.updateMany({
      where: { id, initScriptPid: pid },
      data: { initScriptPid: null },
    });
  }

  /**
   * Clear initOutput field (called when retrying initialization).
   */
  async clearInitOutput(id: string): Promise<void> {
    await prisma.workspace.update({
      where: { id },
      data: { initOutput: null },
    });
  }

  /**
   * Find multiple workspaces by their IDs.
   * Used for batch lookups when enriching process info.
   */
  findByIds(ids: string[]): Promise<Workspace[]> {
    if (ids.length === 0) {
      return Promise.resolve([]);
    }
    return prisma.workspace.findMany({
      where: {
        id: { in: ids },
      },
    });
  }

  /**
   * Find multiple workspaces by their IDs with project included.
   * Used for batch lookups when project info is needed (e.g., admin process list).
   */
  async findByIdsWithProject(ids: string[]): Promise<WorkspaceWithProject[]> {
    if (ids.length === 0) {
      return [];
    }
    const rows = await prisma.workspace.findMany({
      where: {
        id: { in: ids },
      },
      include: { project: true, pr: true, autoIteration: true },
    });
    return rows.map(withProjectAndPR);
  }

  // ---------------------------------------------------------------------------
  // Parent / child workspace hierarchy
  // ---------------------------------------------------------------------------

  /**
   * Find non-archived child workspaces for a given parent.
   */
  findChildrenByParentId(parentId: string): Promise<Workspace[]> {
    return prisma.workspace.findMany({
      where: { parentWorkspaceId: parentId, status: { not: 'ARCHIVED' } },
      orderBy: { createdAt: 'asc' },
    });
  }

  /**
   * Find child workspaces with session counts included, for status summaries.
   */
  async findChildrenWithStatus(parentId: string): Promise<
    Flattened<
      Prisma.WorkspaceGetPayload<{
        include: { agentSessions: true; project: true } & SideTableInclude;
      }>
    >[]
  > {
    const rows = await prisma.workspace.findMany({
      where: { parentWorkspaceId: parentId, status: { not: 'ARCHIVED' } },
      include: { agentSessions: true, project: true, ...sideTables },
      orderBy: { createdAt: 'asc' },
    });
    return rows.map(flatten);
  }

  /**
   * Find the parent workspace summary for a given child workspace id.
   * Returns the parent with project included for cross-project navigation.
   */
  async findParentWorkspace(childId: string): Promise<WorkspaceWithProject | null> {
    const row = await prisma.workspace.findFirst({
      where: { childWorkspaces: { some: { id: childId } } },
      include: { project: true, pr: true, autoIteration: true },
    });
    return row ? withProjectAndPR(row) : null;
  }
}

export const workspaceAccessor = new WorkspaceAccessor();
