-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Workspace" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "worktreePath" TEXT,
    "branchName" TEXT,
    "isAutoGeneratedBranch" BOOLEAN NOT NULL DEFAULT false,
    "isAutoGeneratedName" BOOLEAN NOT NULL DEFAULT false,
    "creationSource" TEXT NOT NULL DEFAULT 'MANUAL',
    "creationMetadata" JSONB,
    "initErrorMessage" TEXT,
    "initOutput" TEXT,
    "initStartedAt" DATETIME,
    "initCompletedAt" DATETIME,
    "initRetryCount" INTEGER NOT NULL DEFAULT 0,
    "runScriptCommand" TEXT,
    "runScriptCleanupCommand" TEXT,
    "runScriptPid" INTEGER,
    "runScriptPort" INTEGER,
    "runScriptStartedAt" DATETIME,
    "runScriptStatus" TEXT NOT NULL DEFAULT 'IDLE',
    "prUrl" TEXT,
    "githubIssueNumber" INTEGER,
    "githubIssueUrl" TEXT,
    "linearIssueId" TEXT,
    "linearIssueIdentifier" TEXT,
    "linearIssueUrl" TEXT,
    "defaultSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "ratchetSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "prNumber" INTEGER,
    "prState" TEXT NOT NULL DEFAULT 'NONE',
    "prReviewState" TEXT,
    "prCiStatus" TEXT NOT NULL DEFAULT 'UNKNOWN',
    "prUpdatedAt" DATETIME,
    "prCiFailedAt" DATETIME,
    "prCiLastNotifiedAt" DATETIME,
    "prReviewLastCheckedAt" DATETIME,
    "prReviewLastCommentId" TEXT,
    "ratchetEnabled" BOOLEAN NOT NULL DEFAULT true,
    "ratchetState" TEXT NOT NULL DEFAULT 'IDLE',
    "ratchetLastCheckedAt" DATETIME,
    "ratchetActiveSessionId" TEXT,
    "ratchetLastCiRunId" TEXT,
    "hasHadSessions" BOOLEAN NOT NULL DEFAULT false,
    "cachedKanbanColumn" TEXT NOT NULL DEFAULT 'WAITING',
    "stateComputedAt" DATETIME,
    CONSTRAINT "Workspace_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_Workspace" ("branchName", "cachedKanbanColumn", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "name", "prCiFailedAt", "prCiLastNotifiedAt", "prCiStatus", "prNumber", "prReviewLastCheckedAt", "prReviewLastCommentId", "prReviewState", "prState", "prUpdatedAt", "prUrl", "projectId", "ratchetActiveSessionId", "ratchetEnabled", "ratchetLastCheckedAt", "ratchetLastCiRunId", "ratchetSessionProvider", "ratchetState", "runScriptCleanupCommand", "runScriptCommand", "runScriptPid", "runScriptPort", "runScriptStartedAt", "runScriptStatus", "stateComputedAt", "status", "updatedAt", "worktreePath") SELECT "branchName", "cachedKanbanColumn", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "name", "prCiFailedAt", "prCiLastNotifiedAt", "prCiStatus", "prNumber", "prReviewLastCheckedAt", "prReviewLastCommentId", "prReviewState", "prState", "prUpdatedAt", "prUrl", "projectId", "ratchetActiveSessionId", "ratchetEnabled", "ratchetLastCheckedAt", "ratchetLastCiRunId", "ratchetSessionProvider", "ratchetState", "runScriptCleanupCommand", "runScriptCommand", "runScriptPid", "runScriptPort", "runScriptStartedAt", "runScriptStatus", "stateComputedAt", "status", "updatedAt", "worktreePath" FROM "Workspace";
DROP TABLE "Workspace";
ALTER TABLE "new_Workspace" RENAME TO "Workspace";
CREATE INDEX "Workspace_projectId_idx" ON "Workspace"("projectId");
CREATE INDEX "Workspace_status_idx" ON "Workspace"("status");
CREATE INDEX "Workspace_cachedKanbanColumn_idx" ON "Workspace"("cachedKanbanColumn");
CREATE INDEX "Workspace_projectId_status_idx" ON "Workspace"("projectId", "status");
CREATE INDEX "Workspace_projectId_cachedKanbanColumn_idx" ON "Workspace"("projectId", "cachedKanbanColumn");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
