-- Split the auto-iteration group off Workspace into its own 1:1 table.
--
-- The last of the four concerns the model carried. Five columns, one concern,
-- copied verbatim -- there is no derived value here and no misnamed column to
-- correct, only the `autoIteration` prefix to drop now that the table name
-- carries it.
--
-- `mode` moves with them. It reads like a general workspace attribute, but every
-- consumer is an auto-iteration consumer, so it is this group's discriminant --
-- the same call the ratchet split made for `ratchetEnabled`. Its NOT NULL
-- default carries over, so a workspace that never used the feature backfills to
-- exactly what it had: STANDARD and four nulls.
--
-- `status` is copied rather than reset even though `resetStaleAutoIterationStatuses`
-- clears RUNNING at the next startup: COMPLETED and FAILED are results the user
-- has not seen yet, and PAUSED is a state the user chose.

CREATE TABLE "WorkspaceAutoIteration" (
    "workspaceId" TEXT NOT NULL PRIMARY KEY,
    "mode" TEXT NOT NULL DEFAULT 'STANDARD',
    "status" TEXT,
    "config" JSONB,
    "progress" JSONB,
    "sessionId" TEXT,
    CONSTRAINT "WorkspaceAutoIteration_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Backfill one row per existing workspace before the columns go away. Every
-- workspace gets a row, including the STANDARD ones that have never touched the
-- feature, so the compare-and-swaps on `sessionId` and `status` always have a
-- row to guard.
INSERT INTO "WorkspaceAutoIteration" ("workspaceId", "mode", "status", "config", "progress", "sessionId")
SELECT "id", "mode", "autoIterationStatus", "autoIterationConfig", "autoIterationProgress", "autoIterationSessionId"
FROM "Workspace";

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Workspace" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "worktreePath" TEXT,
    "branchName" TEXT,
    "isAutoGeneratedBranch" BOOLEAN NOT NULL DEFAULT false,
    "creationSource" TEXT NOT NULL DEFAULT 'MANUAL',
    "creationMetadata" JSONB,
    "initErrorMessage" TEXT,
    "initOutput" TEXT,
    "initStartedAt" DATETIME,
    "initCompletedAt" DATETIME,
    "initScriptPid" INTEGER,
    "initRetryCount" INTEGER NOT NULL DEFAULT 0,
    "githubIssueNumber" INTEGER,
    "githubIssueUrl" TEXT,
    "linearIssueId" TEXT,
    "linearIssueIdentifier" TEXT,
    "linearIssueUrl" TEXT,
    "defaultSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "ratchetSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "periodicTaskId" TEXT,
    "parent_workspace_id" TEXT,
    "hasHadSessions" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "Workspace_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Workspace_periodicTaskId_fkey" FOREIGN KEY ("periodicTaskId") REFERENCES "PeriodicTask" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Workspace_parent_workspace_id_fkey" FOREIGN KEY ("parent_workspace_id") REFERENCES "Workspace" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Workspace" ("branchName", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initScriptPid", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "name", "parent_workspace_id", "periodicTaskId", "projectId", "ratchetSessionProvider", "status", "updatedAt", "worktreePath") SELECT "branchName", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initScriptPid", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "name", "parent_workspace_id", "periodicTaskId", "projectId", "ratchetSessionProvider", "status", "updatedAt", "worktreePath" FROM "Workspace";
DROP TABLE "Workspace";
ALTER TABLE "new_Workspace" RENAME TO "Workspace";
CREATE INDEX "Workspace_projectId_idx" ON "Workspace"("projectId");
CREATE INDEX "Workspace_status_idx" ON "Workspace"("status");
CREATE INDEX "Workspace_parent_workspace_id_idx" ON "Workspace"("parent_workspace_id");
CREATE INDEX "Workspace_projectId_status_idx" ON "Workspace"("projectId", "status");
CREATE INDEX "Workspace_projectId_updatedAt_idx" ON "Workspace"("projectId", "updatedAt");
CREATE INDEX "Workspace_projectId_createdAt_idx" ON "Workspace"("projectId", "createdAt");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- SQLite's RedefineTables above dropped and recreated "Workspace", which drops
-- every trigger attached to it. Recreate the depth-1 guards verbatim; any future
-- migration that redefines this table has to do the same.
CREATE TRIGGER enforce_workspace_depth_1
BEFORE INSERT ON "Workspace"
WHEN NEW."parent_workspace_id" IS NOT NULL
BEGIN
  -- Block self-parenting
  SELECT RAISE(ABORT, 'A workspace cannot be its own parent')
  WHERE NEW."id" = NEW."parent_workspace_id";
  -- Block grandchild chains: proposed parent must not already have a parent
  SELECT RAISE(ABORT, 'Child workspaces cannot have children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "id" = NEW."parent_workspace_id"
    AND "parent_workspace_id" IS NOT NULL
  );
END;

CREATE TRIGGER enforce_workspace_depth_1_update
BEFORE UPDATE ON "Workspace"
WHEN NEW."parent_workspace_id" IS NOT NULL
BEGIN
  -- Block self-parenting
  SELECT RAISE(ABORT, 'A workspace cannot be its own parent')
  WHERE NEW."id" = NEW."parent_workspace_id";
  -- Block grandchild chains: proposed parent must not already have a parent
  SELECT RAISE(ABORT, 'Child workspaces cannot have children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "id" = NEW."parent_workspace_id"
    AND "parent_workspace_id" IS NOT NULL
  );
  -- Block re-parenting a workspace that already has children
  SELECT RAISE(ABORT, 'Cannot re-parent a workspace that already has children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "parent_workspace_id" = NEW."id"
  );
END;
