import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { SessionRepository } from './session.repository';
import type { SessionPermissionPresetPort } from './session-context.service';
import { SessionContextService } from './session-context.service';
import {
  createLifecycleTestSession,
  createLifecycleTestWorkspace,
} from './session-lifecycle.test-helpers';

vi.mock('@/backend/services/logger.service', () => ({
  createLogger: () => ({
    debug: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
  getCurrentProcessEnv: () => ({ NODE_ENV: 'test' }),
}));

vi.mock('@/backend/services/settings', () => {
  throw new Error('Session context unit tests must not load the settings capsule');
});

vi.mock('@/backend/services/workspace', () => ({
  workspaceNotificationService: {},
}));

function createHarness() {
  const session = createLifecycleTestSession();
  const workspace = createLifecycleTestWorkspace({ worktreePath: '/worktree' });
  const repository = {
    getSessionById: vi.fn<SessionRepository['getSessionById']>(async () => session),
    getWorkspaceById: vi.fn<SessionRepository['getWorkspaceById']>(async () => workspace),
  } satisfies Pick<SessionRepository, 'getSessionById' | 'getWorkspaceById'>;
  const permissionPresetPort = {
    getPermissionPreset: vi.fn<SessionPermissionPresetPort['getPermissionPreset']>(async () =>
      Promise.resolve('STRICT')
    ),
  } satisfies SessionPermissionPresetPort;
  const service = new SessionContextService({
    repository,
    permissionPresetPort,
  });

  return { service, session, workspace, repository, permissionPresetPort };
}

describe('SessionContextService', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('returns null when the session does not exist', async () => {
    const { service, repository } = createHarness();
    repository.getSessionById.mockResolvedValueOnce(null);

    await expect(service.load('missing-session')).resolves.toBeNull();

    expect(repository.getWorkspaceById).not.toHaveBeenCalled();
  });

  it('returns null when the workspace has no worktree', async () => {
    const { service, repository, workspace } = createHarness();
    repository.getWorkspaceById.mockResolvedValueOnce({ ...workspace, worktreePath: null });

    await expect(service.load('session-1')).resolves.toBeNull();
  });

  it('constructs options for resuming the provider session', async () => {
    const { service, repository, session, workspace } = createHarness();
    repository.getSessionById.mockResolvedValueOnce({
      ...session,
      providerSessionId: 'provider-session-1',
    });
    expect(await service.getOptions(session.id)).toEqual({
      workingDir: '/worktree',
      resumeProviderSessionId: 'provider-session-1',
      model: session.model,
      workspaceStatus: workspace.status,
    });
  });

  it('loads child session options without querying unused prompt context', async () => {
    const { service, repository, workspace } = createHarness();
    repository.getWorkspaceById.mockResolvedValue({
      ...workspace,
      parentWorkspaceId: 'parent-workspace',
      isAutoGeneratedBranch: true,
      hasHadSessions: false,
    });
    expect(await service.getOptions('session-1')).toEqual({
      workingDir: '/worktree',
      resumeProviderSessionId: undefined,
      model: 'claude-sonnet',
      workspaceStatus: 'READY',
    });
    expect(repository.getWorkspaceById).toHaveBeenCalledTimes(1);
  });

  it.each([
    { workflow: 'code', preset: 'STRICT' as const },
    { workflow: 'ratchet', preset: 'YOLO' as const },
  ])('uses the configured $workflow permission preset', async ({ workflow, preset }) => {
    const { service, session, permissionPresetPort } = createHarness();
    permissionPresetPort.getPermissionPreset.mockResolvedValueOnce(preset);

    await expect(service.resolvePermissionPreset({ ...session, workflow })).resolves.toBe(preset);

    expect(permissionPresetPort.getPermissionPreset).toHaveBeenCalledWith(workflow);
  });

  it.each([
    { workflow: 'code', fallback: 'STRICT' as const },
    { workflow: 'ratchet', fallback: 'YOLO' as const },
  ])(
    'uses the $fallback fallback when $workflow permission settings cannot be read',
    async ({ workflow, fallback }) => {
      const { service, session, permissionPresetPort } = createHarness();
      permissionPresetPort.getPermissionPreset.mockRejectedValueOnce(new Error('settings failed'));

      await expect(service.resolvePermissionPreset({ ...session, workflow })).resolves.toBe(
        fallback
      );
    }
  );
});
