import { createLogger } from '@/backend/services/logger.service';
import type { AgentSessionRecord } from '@/backend/services/session/resources/agent-session.accessor';
import type { PermissionPreset } from '@/backend/services/session/service/acp';
import type { WorkspaceStatus } from '@/shared/core';
import type { SessionPromptBuilder } from './session.prompt-builder';
import type { SessionRepository } from './session.repository';

const logger = createLogger('session');

export type SessionContext = Readonly<{
  session: AgentSessionRecord;
  workingDir: string;
  resumeProviderSessionId: string | undefined;
  systemPrompt: string | undefined;
  model: string;
  workspaceId: string;
  workspaceStatus: WorkspaceStatus;
  parentWorkspaceId: string | null;
}>;

export interface SessionPermissionPresetPort {
  getPermissionPreset(workflow: string): Promise<PermissionPreset>;
}

type SessionContextServiceDependencies = {
  repository: Pick<SessionRepository, 'getSessionById' | 'getWorkspaceById' | 'getProjectById'>;
  promptBuilder: Pick<SessionPromptBuilder, 'shouldInjectBranchRename' | 'buildSystemPrompt'>;
  permissionPresetPort: SessionPermissionPresetPort;
};

type ParentWorkspaceContext = {
  parentWorkspaceName?: string;
  parentProjectName?: string;
  reportBackOn?: string;
};

export class SessionContextService {
  constructor(private readonly dependencies: SessionContextServiceDependencies) {}

  async load(
    sessionId: string,
    preloadedSession?: AgentSessionRecord
  ): Promise<SessionContext | null> {
    const session =
      preloadedSession ?? (await this.dependencies.repository.getSessionById(sessionId));
    if (!session) {
      logger.warn('Session not found when getting options', { sessionId });
      return null;
    }

    const workspace = await this.dependencies.repository.getWorkspaceById(session.workspaceId);
    if (!workspace?.worktreePath) {
      logger.warn('Workspace or worktree not found', {
        sessionId,
        workspaceId: session.workspaceId,
      });
      return null;
    }

    const shouldInjectBranchRename = this.dependencies.promptBuilder.shouldInjectBranchRename({
      branchName: workspace.branchName,
      isAutoGeneratedBranch: workspace.isAutoGeneratedBranch,
      hasHadSessions: workspace.hasHadSessions,
    });
    const project = shouldInjectBranchRename
      ? await this.dependencies.repository.getProjectById(workspace.projectId)
      : null;
    if (shouldInjectBranchRename && !project) {
      logger.warn('Project not found when building branch rename instruction', {
        sessionId,
        projectId: workspace.projectId,
      });
    }

    const parentContext = await this.resolveParentWorkspaceContext(workspace);
    const { workflowPrompt, systemPrompt, injectedBranchRename } =
      this.dependencies.promptBuilder.buildSystemPrompt({
        workflow: session.workflow,
        workspace: {
          branchName: workspace.branchName,
          isAutoGeneratedBranch: workspace.isAutoGeneratedBranch,
          hasHadSessions: workspace.hasHadSessions,
          name: workspace.name,
          description: workspace.description ?? undefined,
          runScriptPort: workspace.runScriptPort,
          parentWorkspaceId: workspace.parentWorkspaceId,
          parentWorkspaceName: parentContext.parentWorkspaceName,
          parentProjectName: parentContext.parentProjectName,
          reportBackOn: parentContext.reportBackOn,
        },
        project,
      });

    logger.info('Loaded workflow prompt for session options', {
      sessionId,
      workflow: session.workflow,
      hasPrompt: !!workflowPrompt,
      promptLength: workflowPrompt?.length ?? 0,
    });
    if (injectedBranchRename) {
      logger.info('Injected branch rename instruction', {
        sessionId,
        branchName: workspace.branchName,
        branchPrefix: project?.githubOwner,
      });
    }

    return {
      session,
      workingDir: workspace.worktreePath,
      resumeProviderSessionId: session.providerSessionId ?? undefined,
      systemPrompt,
      model: session.model,
      workspaceId: workspace.id,
      workspaceStatus: workspace.status,
      parentWorkspaceId: workspace.parentWorkspaceId,
    };
  }

  async getOptions(
    sessionId: string
  ): Promise<Omit<SessionContext, 'session' | 'workspaceId' | 'parentWorkspaceId'> | null> {
    const context = await this.load(sessionId);
    if (!context) {
      return null;
    }
    return {
      workingDir: context.workingDir,
      resumeProviderSessionId: context.resumeProviderSessionId,
      systemPrompt: context.systemPrompt,
      model: context.model,
      workspaceStatus: context.workspaceStatus,
    };
  }

  async resolvePermissionPreset(session: AgentSessionRecord): Promise<PermissionPreset> {
    const fallback: PermissionPreset = session.workflow === 'ratchet' ? 'YOLO' : 'STRICT';
    try {
      return await this.dependencies.permissionPresetPort.getPermissionPreset(session.workflow);
    } catch (error) {
      logger.warn('Failed loading user permission preset; using default', {
        workflow: session.workflow,
        error: error instanceof Error ? error.message : String(error),
      });
      return fallback;
    }
  }

  private async resolveParentWorkspaceContext(workspace: {
    parentWorkspaceId: string | null;
    creationMetadata: unknown;
  }): Promise<ParentWorkspaceContext> {
    if (!workspace.parentWorkspaceId) {
      return {};
    }
    let parentWorkspaceName: string | undefined;
    let parentProjectName: string | undefined;
    const parentWorkspace = await this.dependencies.repository.getWorkspaceById(
      workspace.parentWorkspaceId
    );
    if (parentWorkspace) {
      parentWorkspaceName = parentWorkspace.name;
      const parentProject = await this.dependencies.repository.getProjectById(
        parentWorkspace.projectId
      );
      parentProjectName = parentProject?.name;
    }
    const metadata = workspace.creationMetadata as Record<string, unknown> | null;
    const reportBackOn =
      typeof metadata?.reportBackOn === 'string' ? metadata.reportBackOn : undefined;
    return { parentWorkspaceName, parentProjectName, reportBackOn };
  }
}
