import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { SessionPromptBuilder } from './session.prompt-builder';
import type { SessionRepository } from './session.repository';
import type { SessionPermissionPresetPort } from './session-context.service';
import { SessionContextService } from './session-context.service';
import {
  createLifecycleTestSession,
  createLifecycleTestWorkspace,
} from './session-lifecycle.test-helpers';

vi.mock('@/backend/services/logger.service', () => ({
  createLogger: () => ({
    debug: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
  getCurrentProcessEnv: () => ({ NODE_ENV: 'test' }),
}));

function createHarness() {
  const session = createLifecycleTestSession();
  const workspace = createLifecycleTestWorkspace({ worktreePath: '/worktree' });
  const repository = {
    getSessionById: vi.fn<SessionRepository['getSessionById']>(async () => session),
    getWorkspaceById: vi.fn<SessionRepository['getWorkspaceById']>(async () => workspace),
    getProjectById: vi.fn<SessionRepository['getProjectById']>(async () => null),
  } satisfies Pick<SessionRepository, 'getSessionById' | 'getWorkspaceById' | 'getProjectById'>;
  const promptBuilder = {
    shouldInjectBranchRename: vi.fn<SessionPromptBuilder['shouldInjectBranchRename']>(() => false),
    buildSystemPrompt: vi.fn<SessionPromptBuilder['buildSystemPrompt']>(() => ({
      workflowPrompt: undefined,
      systemPrompt: 'system prompt',
      injectedBranchRename: false,
    })),
  } satisfies Pick<SessionPromptBuilder, 'shouldInjectBranchRename' | 'buildSystemPrompt'>;
  const permissionPresetPort = {
    getPermissionPreset: vi.fn<SessionPermissionPresetPort['getPermissionPreset']>(async () =>
      Promise.resolve('STRICT')
    ),
  } satisfies SessionPermissionPresetPort;
  const service = new SessionContextService({
    repository,
    promptBuilder,
    permissionPresetPort,
  });

  return { service, session, workspace, repository, promptBuilder, permissionPresetPort };
}

describe('SessionContextService', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('returns null when the session does not exist', async () => {
    const { service, repository } = createHarness();
    repository.getSessionById.mockResolvedValueOnce(null);

    await expect(service.load('missing-session')).resolves.toBeNull();

    expect(repository.getWorkspaceById).not.toHaveBeenCalled();
  });

  it('returns null when the workspace has no worktree', async () => {
    const { service, repository, workspace } = createHarness();
    repository.getWorkspaceById.mockResolvedValueOnce({ ...workspace, worktreePath: null });

    await expect(service.load('session-1')).resolves.toBeNull();
  });

  it('loads the project needed for branch-rename prompt construction', async () => {
    const { service, repository, promptBuilder, workspace } = createHarness();
    const branchWorkspace = {
      ...workspace,
      branchName: 'factory-task',
      isAutoGeneratedBranch: true,
      hasHadSessions: false,
    };
    const project = {
      id: 'project-1',
      name: 'Project',
      githubOwner: 'purplefish-ai',
    };
    repository.getWorkspaceById.mockResolvedValueOnce(branchWorkspace);
    repository.getProjectById.mockResolvedValueOnce(project as never);
    promptBuilder.shouldInjectBranchRename.mockReturnValueOnce(true);

    const result = await service.load('session-1');

    expect(repository.getProjectById).toHaveBeenCalledWith('project-1');
    expect(promptBuilder.buildSystemPrompt).toHaveBeenCalledWith(
      expect.objectContaining({ project })
    );
    expect(result).toMatchObject({ workingDir: '/worktree', systemPrompt: 'system prompt' });
  });

  it('still constructs the prompt when a branch-rename project is missing', async () => {
    const { service, repository, promptBuilder } = createHarness();
    promptBuilder.shouldInjectBranchRename.mockReturnValueOnce(true);
    repository.getProjectById.mockResolvedValueOnce(null);

    const result = await service.load('session-1');

    expect(promptBuilder.buildSystemPrompt).toHaveBeenCalledWith(
      expect.objectContaining({ project: null })
    );
    expect(result?.systemPrompt).toBe('system prompt');
  });

  it('builds child context through injected repository and settings ports', async () => {
    const { service, repository, promptBuilder, workspace } = createHarness();
    const childWorkspace = {
      ...workspace,
      parentWorkspaceId: 'parent-workspace',
      creationMetadata: { reportBackOn: 'completion' },
    };
    const parentWorkspace = createLifecycleTestWorkspace({
      id: 'parent-workspace',
      name: 'Parent',
      projectId: 'parent-project',
    });
    repository.getWorkspaceById.mockImplementation(async (workspaceId) =>
      workspaceId === 'parent-workspace' ? parentWorkspace : childWorkspace
    );
    repository.getProjectById.mockResolvedValueOnce({
      id: 'parent-project',
      name: 'Parent Project',
    } as never);

    const result = await service.load('session-1');

    expect(promptBuilder.buildSystemPrompt).toHaveBeenCalledWith(
      expect.objectContaining({
        workspace: expect.objectContaining({
          parentWorkspaceName: 'Parent',
          parentProjectName: 'Parent Project',
          reportBackOn: 'completion',
        }),
      })
    );
    expect(result).toMatchObject({
      session: expect.objectContaining({ id: 'session-1' }),
      workingDir: '/worktree',
      workspaceId: 'workspace-1',
      parentWorkspaceId: 'parent-workspace',
    });
  });

  it('constructs normal session options without loading a project', async () => {
    const { service, repository, promptBuilder, session, workspace } = createHarness();
    const resumedSession = { ...session, providerSessionId: 'provider-session-1' };
    repository.getSessionById.mockResolvedValueOnce(resumedSession);
    promptBuilder.buildSystemPrompt.mockReturnValueOnce({
      workflowPrompt: 'workflow prompt',
      systemPrompt: 'normal system prompt',
      injectedBranchRename: false,
    });

    const result = await service.getOptions(resumedSession.id);

    expect(repository.getProjectById).not.toHaveBeenCalled();
    expect(promptBuilder.buildSystemPrompt).toHaveBeenCalledWith({
      workflow: session.workflow,
      workspace: {
        branchName: workspace.branchName,
        isAutoGeneratedBranch: workspace.isAutoGeneratedBranch,
        hasHadSessions: workspace.hasHadSessions,
        name: workspace.name,
        description: undefined,
        runScriptPort: workspace.runScriptPort,
        parentWorkspaceId: workspace.parentWorkspaceId,
        parentWorkspaceName: undefined,
        parentProjectName: undefined,
        reportBackOn: undefined,
      },
      project: null,
    });
    expect(result).toEqual({
      workingDir: '/worktree',
      resumeProviderSessionId: 'provider-session-1',
      systemPrompt: 'normal system prompt',
      model: session.model,
      workspaceStatus: workspace.status,
    });
  });

  it.each([
    { workflow: 'code', preset: 'STRICT' as const },
    { workflow: 'ratchet', preset: 'YOLO' as const },
  ])('uses the configured $workflow permission preset', async ({ workflow, preset }) => {
    const { service, session, permissionPresetPort } = createHarness();
    permissionPresetPort.getPermissionPreset.mockResolvedValueOnce(preset);

    await expect(service.resolvePermissionPreset({ ...session, workflow })).resolves.toBe(preset);

    expect(permissionPresetPort.getPermissionPreset).toHaveBeenCalledWith(workflow);
  });

  it.each([
    { workflow: 'code', fallback: 'STRICT' as const },
    { workflow: 'ratchet', fallback: 'YOLO' as const },
  ])('uses the $fallback fallback when $workflow permission settings cannot be read', async ({
    workflow,
    fallback,
  }) => {
    const { service, session, permissionPresetPort } = createHarness();
    permissionPresetPort.getPermissionPreset.mockRejectedValueOnce(new Error('settings failed'));

    await expect(service.resolvePermissionPreset({ ...session, workflow })).resolves.toBe(fallback);
  });
});
