/**
 * Fun words for workspace names.
 * Pick one randomly, append a number if there's a conflict.
 */
export const WORKSPACE_WORDS = [
  // Animals
  'tiger',
  'falcon',
  'otter',
  'panda',
  'wolf',
  'fox',
  'bear',
  'hawk',
  'owl',
  'raven',
  'dolphin',
  'eagle',
  'lynx',
  'cobra',
  'jaguar',
  'panther',
  'phoenix',
  'dragon',
  'griffin',
  'sphinx',
  // Space
  'nova',
  'comet',
  'nebula',
  'quasar',
  'pulsar',
  'orbit',
  'cosmos',
  'stellar',
  'lunar',
  'solar',
  // Elements/Nature
  'thunder',
  'blaze',
  'frost',
  'storm',
  'ember',
  'crystal',
  'aurora',
  'summit',
  'canyon',
  'ridge',
  // Tech/Abstract
  'pixel',
  'vector',
  'cipher',
  'spark',
  'pulse',
  'flux',
  'apex',
  'vertex',
  'nexus',
  'prism',
];

/**
 * Pick a random word from the list
 */
export function pickRandomWord(): string {
  const selected = WORKSPACE_WORDS[Math.floor(Math.random() * WORKSPACE_WORDS.length)];
  return selected ?? 'workspace';
}

/**
 * Generate a unique workspace name given existing names.
 * Picks a random word, appends a number if there's a conflict.
 */
export function generateUniqueWorkspaceName(existingNames: string[]): string {
  const baseWord = pickRandomWord();

  // Check if the base word is available
  if (!existingNames.includes(baseWord)) {
    return baseWord;
  }

  // Find the next available number (with safety limit)
  let counter = 2;
  const maxIterations = 1000;
  while (counter < maxIterations && existingNames.includes(`${baseWord}-${counter}`)) {
    counter++;
  }

  return `${baseWord}-${counter}`;
}

/**
 * Check if a workspace name matches the auto-generated pattern.
 * Auto-generated names are:
 * - A word from WORKSPACE_WORDS
 * - A word from WORKSPACE_WORDS followed by "-" and a number
 */
export function isAutoGeneratedWorkspaceName(name: string): boolean {
  // Check if it's exactly one of the workspace words
  if (WORKSPACE_WORDS.includes(name)) {
    return true;
  }

  // Check if it's a workspace word followed by a number (e.g., "tiger-2")
  const match = /^(.+)-(\d+)$/.exec(name);
  if (match) {
    const baseWord = match[1];
    return baseWord !== undefined && WORKSPACE_WORDS.includes(baseWord);
  }

  return false;
}
