import { z } from 'zod';
/**
 * Shared schema for export/import data validation.
 *
 * This schema is used by both the backend (for export/import operations)
 * and the frontend (for pre-validation of import files).
 *
 * Note: Uses string enums instead of Prisma enums to avoid pulling
 * Prisma client into the browser bundle.
 */
import {
  CIStatus as CoreCIStatus,
  IssueProvider as CoreIssueProvider,
  PRState as CorePRState,
  RatchetReviewTriggerMode as CoreRatchetReviewTriggerMode,
  RatchetState as CoreRatchetState,
  RunScriptStatus as CoreRunScriptStatus,
  SessionPermissionPreset as CoreSessionPermissionPreset,
  SessionProvider as CoreSessionProvider,
  SessionStatus as CoreSessionStatus,
  WorkspaceCreationSource as CoreWorkspaceCreationSource,
  WorkspaceMode as CoreWorkspaceMode,
  WorkspaceProviderSelection as CoreWorkspaceProviderSelection,
  WorkspaceStatus as CoreWorkspaceStatus,
} from '@/shared/core';
import {
  DEFAULT_DEEPGRAM_TTS_MODEL,
  DEFAULT_DEEPGRAM_TTS_SPEED,
  normalizeDeepgramTtsSpeed,
  normalizeDeepgramVoiceModel,
} from '@/shared/deepgram-voices';
import {
  DEFAULT_VOICE_BARGE_IN_SUSTAINED_MS,
  DEFAULT_VOICE_UTTERANCE_END_MS,
  VOICE_BARGE_IN_SUSTAINED_MS_MAX,
  VOICE_BARGE_IN_SUSTAINED_MS_MIN,
  VOICE_UTTERANCE_END_MS_MAX,
  VOICE_UTTERANCE_END_MS_MIN,
} from '@/shared/voice-vad';
import { autoIterationConfigSchema } from './auto-iteration.schema';
import { validateBackupPRs, validateLegacyFixerOwnership } from './export-data-pr-validation';
import {
  prAssociationBackupSchema,
  prDiscoveryBackupSchema,
  prEventBackupSchema,
  prMonitoringBackupSchema,
} from './pr-monitoring-backup.schema';

function enumValues<const T extends Record<string, string>>(enumObject: T) {
  return Object.values(enumObject) as [T[keyof T], ...T[keyof T][]];
}

// Use core as the single enum source-of-truth (browser-safe, no Prisma dependency).
const WorkspaceStatus = z.enum(enumValues(CoreWorkspaceStatus));
const WorkspaceCreationSource = z.enum(enumValues(CoreWorkspaceCreationSource));
const IssueProvider = z.enum(enumValues(CoreIssueProvider));
const RunScriptStatus = z.enum(enumValues(CoreRunScriptStatus));
const WorkspaceMode = z.enum(enumValues(CoreWorkspaceMode));
const PRState = z.enum(enumValues(CorePRState));
const CIStatus = z.enum(enumValues(CoreCIStatus));
const RatchetState = z.enum(enumValues(CoreRatchetState));
const RatchetReviewTriggerMode = z.enum(enumValues(CoreRatchetReviewTriggerMode));
const SessionStatus = z.enum(enumValues(CoreSessionStatus));
const SessionProvider = z.enum(enumValues(CoreSessionProvider));
const SessionPermissionPreset = z.enum(enumValues(CoreSessionPermissionPreset));
const WorkspaceProviderSelection = z.enum(enumValues(CoreWorkspaceProviderSelection));

const exportedProjectSchema = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string().min(1),
  repoPath: z.string(),
  worktreeBasePath: z.string().min(1),
  defaultBranch: z.string(),
  githubOwner: z.string().nullable(),
  githubRepo: z.string().nullable(),
  issueProvider: IssueProvider,
  issueTrackerConfig: z.unknown().nullable(),
  isArchived: z.boolean(),
  startupScriptCommand: z.string().nullable(),
  startupScriptPath: z.string().nullable(),
  startupScriptTimeout: z.number(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const exportedWorkspaceSchema = z.object({
  prs: z.array(prAssociationBackupSchema).optional().default([]),
  prDiscovery: prDiscoveryBackupSchema.nullable().optional().default(null),
  prMonitoring: prMonitoringBackupSchema.nullable().optional().default(null),
  prEvents: z.array(prEventBackupSchema).optional().default([]),
  id: z.string(),
  projectId: z.string(),
  parentWorkspaceId: z.string().nullable().optional().default(null),
  name: z.string(),
  description: z.string().nullable(),
  status: WorkspaceStatus,
  worktreePath: z.string().nullable(),
  branchName: z.string().nullable(),
  isAutoGeneratedBranch: z.boolean(),
  creationSource: WorkspaceCreationSource,
  creationMetadata: z.unknown().nullable(),
  initErrorMessage: z.string().nullable(),
  initOutput: z.string().nullable(),
  initStartedAt: z.string().nullable(),
  initCompletedAt: z.string().nullable(),
  initRetryCount: z.number(),
  runScriptCommand: z.string().nullable(),
  runScriptCleanupCommand: z.string().nullable(),
  runScriptPid: z.number().nullable(),
  runScriptPort: z.number().nullable(),
  runScriptStartedAt: z.string().nullable(),
  runScriptStatus: RunScriptStatus,
  mode: WorkspaceMode.optional().default('STANDARD'),
  autoIterationConfig: autoIterationConfigSchema.nullable().optional().default(null),
  prUrl: z.string().nullable(),
  githubIssueNumber: z.number().nullable(),
  githubIssueUrl: z.string().nullable(),
  linearIssueId: z.string().nullable(),
  linearIssueIdentifier: z.string().nullable(),
  linearIssueUrl: z.string().nullable(),
  defaultSessionProvider: WorkspaceProviderSelection,
  ratchetSessionProvider: WorkspaceProviderSelection.optional(),
  prNumber: z.number().nullable(),
  prState: PRState,
  prReviewState: z.string().nullable(),
  prCiStatus: CIStatus,
  prUpdatedAt: z.string().nullable(),
  prCiFailedAt: z.string().nullable(),
  prCiLastNotifiedAt: z.string().nullable(),
  prReviewLastCheckedAt: z.string().nullable(),
  prReviewLastCommentId: z.string().nullable(),
  ratchetEnabled: z.boolean(),
  ratchetState: RatchetState,
  ratchetLastCheckedAt: z.string().nullable(),
  ratchetActiveSessionId: z.string().nullable(),
  // Carries what the database now calls `WorkspaceRatchet.dispatchSnapshotKey`.
  // The export name is deliberately left alone: it is required at
  // `schemaVersion: 4` with no migration path, so renaming it would make every
  // backup file already on disk fail validation.
  ratchetLastCiRunId: z.string().nullable(),
  hasHadSessions: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const exportedAgentSessionSchema = z.object({
  id: z.string(),
  workspaceId: z.string(),
  name: z.string().nullable(),
  workflow: z.string(),
  workspacePrId: z.string().nullable().optional().default(null),
  model: z.string(),
  status: SessionStatus,
  provider: SessionProvider,
  providerSessionId: z.string().nullable(),
  providerProjectPath: z.string().nullable(),
  providerProcessPid: z.number().nullable(),
  providerMetadata: z.unknown().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const exportedTerminalSessionSchema = z.object({
  id: z.string(),
  workspaceId: z.string(),
  name: z.string().nullable(),
  status: SessionStatus,
  pid: z.number().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const exportedUserSettingsSchema = z.object({
  preferredIde: z.string(),
  customIdeCommand: z.string().nullable(),
  playSoundOnComplete: z.boolean(),
  notificationSoundPath: z.string().nullable(),
  ratchetEnabled: z.boolean(),
  ratchetReplyToPrComments: z.boolean().optional().default(true),
  ratchetReviewTriggerMode: RatchetReviewTriggerMode.optional().default('CHANGES_REQUESTED'),
  defaultSessionProvider: SessionProvider,
  defaultClaudeModel: z.string().optional().default('sonnet'),
  defaultCodexModel: z.string().optional().default('default'),
  defaultClaudeReasoningEffort: z.string().nullable().optional().default(null),
  defaultCodexReasoningEffort: z.string().nullable().optional().default(null),
  defaultWorkspacePermissions: SessionPermissionPreset.optional().default('STRICT'),
  ratchetPermissions: SessionPermissionPreset.optional(),
  autoIterationPermissions: SessionPermissionPreset.optional(),
  // Adversarial review settings
  reviewerSessionProvider: SessionProvider.optional().default('CODEX'),
  reviewerClaudeModel: z.string().nullable().optional().default(null),
  reviewerCodexModel: z.string().nullable().optional().default(null),
  postReviewToGitHub: z.boolean().optional().default(true),
  // Voice mode: the Deepgram API key is intentionally excluded (secret, and
  // scoped per-install), but the enabled toggle and selected voice/speed are
  // just preferences. A restored install still needs its own key before
  // voiceModeEnabled has any effect (getConfig/mintGrantToken both require
  // deepgramApiKeyEncrypted), so restoring the toggle as-is is safe.
  // A backup taken before the Flux upgrade still carries an `aura-2-*` voice
  // (and possibly a speed below the current floor). Import writes these
  // straight to UserSettings without replaying the migration, so normalize
  // here instead of letting a restore reinstate a value Flux rejects.
  voiceModeEnabled: z.boolean().optional().default(false),
  voiceTtsModel: z
    .string()
    .optional()
    .default(DEFAULT_DEEPGRAM_TTS_MODEL)
    .transform(normalizeDeepgramVoiceModel),
  voiceTtsSpeed: z
    .number()
    .optional()
    .default(DEFAULT_DEEPGRAM_TTS_SPEED)
    .transform(normalizeDeepgramTtsSpeed),
  voiceUtteranceEndMs: z
    .number()
    .int()
    .min(VOICE_UTTERANCE_END_MS_MIN)
    .max(VOICE_UTTERANCE_END_MS_MAX)
    .optional()
    .default(DEFAULT_VOICE_UTTERANCE_END_MS),
  voiceBargeInSustainedMs: z
    .number()
    .int()
    .min(VOICE_BARGE_IN_SUSTAINED_MS_MIN)
    .max(VOICE_BARGE_IN_SUSTAINED_MS_MAX)
    .optional()
    .default(DEFAULT_VOICE_BARGE_IN_SUSTAINED_MS),
});

const legacyAndCurrentSchema = z.object({
  meta: z.object({
    exportedAt: z.string(),
    version: z.string(),
    schemaVersion: z.union([z.literal(4), z.literal(5), z.literal(6)]),
  }),
  data: z.object({
    projects: z.array(exportedProjectSchema),
    workspaces: z.array(exportedWorkspaceSchema),
    agentSessions: z.array(exportedAgentSessionSchema),
    terminalSessions: z.array(exportedTerminalSessionSchema),
    userSettings: exportedUserSettingsSchema.nullable(),
  }),
});

const legacyPRSchema = prAssociationBackupSchema.extend({
  ratchet: z.object({
    lastCheckedAt: z.string().nullable(),
    activeSessionId: z.string().nullable(),
    dispatchSnapshotKey: z.string().nullable(),
    dispatchOutcome: z.enum(['RUNNING', 'COMPLETED', 'DIED']).nullable(),
    dispatchRetryCount: z.number().int().nonnegative(),
    dispatchStalled: z.boolean(),
  }),
});
const publishedVersion5Schema = legacyAndCurrentSchema
  .extend({
    meta: legacyAndCurrentSchema.shape.meta.extend({ schemaVersion: z.literal(5) }),
    data: legacyAndCurrentSchema.shape.data.extend({
      workspaces: z.array(
        exportedWorkspaceSchema
          .omit({
            prUrl: true,
            prNumber: true,
            prState: true,
            prReviewState: true,
            prCiStatus: true,
            prUpdatedAt: true,
            prCiFailedAt: true,
            prCiLastNotifiedAt: true,
            prReviewLastCheckedAt: true,
            prReviewLastCommentId: true,
            ratchetLastCiRunId: true,
            ratchetState: true,
          })
          .extend({
            prs: z.array(legacyPRSchema),
            ratchetActivePrId: z.string().nullable(),
          })
      ),
    }),
  })
  .superRefine(validateLegacyFixerOwnership);

function normalizePublishedVersion5(data: z.infer<typeof publishedVersion5Schema>) {
  return {
    ...data,
    meta: { ...data.meta, schemaVersion: 6 as const },
    data: {
      ...data.data,
      workspaces: data.data.workspaces.map((workspace) => {
        const legacySessionIds = [
          ...new Set([
            ...(workspace.ratchetActiveSessionId ? [workspace.ratchetActiveSessionId] : []),
            ...workspace.prs.flatMap((pr) =>
              pr.ratchet.activeSessionId ? [pr.ratchet.activeSessionId] : []
            ),
            ...data.data.agentSessions
              .filter((s) => s.workspaceId === workspace.id && s.workflow === 'ratchet')
              .map((s) => s.id),
          ]),
        ];
        return exportedWorkspaceSchema.parse({
          ...workspace,
          prs: workspace.prs.map(({ ratchet: _ratchet, ...pr }) => pr),
          prUrl: null,
          prNumber: null,
          prState: 'NONE',
          prReviewState: null,
          prCiStatus: 'UNKNOWN',
          prUpdatedAt: null,
          prCiFailedAt: null,
          prCiLastNotifiedAt: null,
          prReviewLastCheckedAt: null,
          prReviewLastCommentId: null,
          ratchetLastCiRunId: null,
          ratchetState: 'IDLE',
          ratchetActiveSessionId: null,
          prMonitoring: {
            enabled: workspace.ratchetEnabled,
            recipientSessionId: null,
            bindingRevision: 0,
            eventEpoch: workspace.ratchetEnabled ? 1 : 0,
            deliveryPauseReason: legacySessionIds.length ? 'LEGACY_FIXER' : null,
            legacySessionIds,
            lastCheckedAt: workspace.ratchetLastCheckedAt,
          },
        });
      }),
    },
  };
}
function normalizeLegacyAndCurrent(data: z.infer<typeof legacyAndCurrentSchema>) {
  if (data.meta.schemaVersion === 6) {
    return { ...data, meta: { ...data.meta, schemaVersion: 6 as const } };
  }
  const workspaces = data.data.workspaces.map((workspace) => {
    const legacySessionIds = [
      ...new Set([
        ...(workspace.ratchetActiveSessionId ? [workspace.ratchetActiveSessionId] : []),
        ...data.data.agentSessions
          .filter((s) => s.workspaceId === workspace.id && s.workflow === 'ratchet')
          .map((s) => s.id),
      ]),
    ];
    const prs =
      data.meta.schemaVersion === 4
        ? workspace.prUrl
          ? [
              prAssociationBackupSchema.parse({
                id: `legacy-pr-${workspace.id}`,
                url: workspace.prUrl,
                number: workspace.prNumber,
                title: null,
                headRefName: null,
                baseRefName: null,
                state: workspace.prState,
                reviewState: workspace.prReviewState,
                ciStatus: workspace.prCiStatus,
                hasMergeConflict: workspace.ratchetState === 'MERGE_CONFLICT',
                syncedAt: workspace.prUpdatedAt,
                detachedAt: null,
                revision: 0,
                ciFailedAt: workspace.prCiFailedAt,
                ciLastNotifiedAt: workspace.prCiLastNotifiedAt,
                reviewLastCheckedAt: workspace.prReviewLastCheckedAt,
                reviewLastCommentId: workspace.prReviewLastCommentId,
              }),
            ]
          : []
        : workspace.prs;
    return {
      ...workspace,
      prs,
      prMonitoring: workspace.prMonitoring ?? {
        enabled: workspace.ratchetEnabled,
        recipientSessionId: null,
        bindingRevision: 0,
        eventEpoch: workspace.ratchetEnabled ? 1 : 0,
        deliveryPauseReason: legacySessionIds.length ? 'LEGACY_FIXER' : null,
        legacySessionIds,
        lastCheckedAt: workspace.ratchetLastCheckedAt,
      },
    };
  });
  const agentSessions = data.data.agentSessions.map((session) => {
    const workspace = workspaces.find((w) => w.id === session.workspaceId);
    return data.meta.schemaVersion === 4 && workspace?.ratchetActiveSessionId === session.id
      ? { ...session, workspacePrId: workspace.prs[0]?.id ?? null }
      : session;
  });
  return {
    ...data,
    meta: { ...data.meta, schemaVersion: 6 as const },
    data: { ...data.data, workspaces, agentSessions },
  };
}
function safelyNormalize<T, R>(
  input: T,
  ctx: z.RefinementCtx,
  normalize: (input: T) => R
): R | typeof z.NEVER {
  try {
    return normalize(input);
  } catch (error) {
    if (!(error instanceof z.ZodError)) {
      throw error;
    }
    for (const issue of error.issues) {
      ctx.addIssue({ ...issue });
    }
    return z.NEVER;
  }
}
export const exportDataSchema = z
  .union([
    publishedVersion5Schema.transform((input, ctx) =>
      safelyNormalize(input, ctx, normalizePublishedVersion5)
    ),
    legacyAndCurrentSchema.transform((input, ctx) =>
      safelyNormalize(input, ctx, normalizeLegacyAndCurrent)
    ),
  ])
  .superRefine(validateBackupPRs);

export {
  exportedAgentSessionSchema,
  exportedProjectSchema,
  exportedTerminalSessionSchema,
  exportedUserSettingsSchema,
  exportedWorkspaceSchema,
};

export type ExportData = z.infer<typeof exportDataSchema>;
