/**
 * Shared schema for export/import data validation.
 *
 * This schema is used by both the backend (for export/import operations)
 * and the frontend (for pre-validation of import files).
 *
 * Note: Uses string enums instead of Prisma enums to avoid pulling
 * Prisma client into the browser bundle.
 */

import { z } from 'zod';

// Enum values copied from Prisma schema to avoid Prisma client dependency
const WorkspaceStatus = z.enum(['NEW', 'PROVISIONING', 'READY', 'FAILED', 'ARCHIVED']);
const WorkspaceCreationSource = z.enum(['MANUAL', 'RESUME_BRANCH', 'GITHUB_ISSUE']);
const RunScriptStatus = z.enum(['IDLE', 'STARTING', 'RUNNING', 'STOPPING', 'COMPLETED', 'FAILED']);
const PRState = z.enum([
  'NONE',
  'DRAFT',
  'OPEN',
  'CHANGES_REQUESTED',
  'APPROVED',
  'MERGED',
  'CLOSED',
]);
const CIStatus = z.enum(['UNKNOWN', 'PENDING', 'SUCCESS', 'FAILURE']);
const KanbanColumn = z.enum(['WORKING', 'WAITING', 'DONE']);
const RatchetState = z.enum([
  'IDLE',
  'CI_RUNNING',
  'CI_FAILED',
  'REVIEW_PENDING',
  'READY',
  'MERGED',
]);
const SessionStatus = z.enum(['IDLE', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED']);

const exportedProjectSchema = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  repoPath: z.string(),
  worktreeBasePath: z.string(),
  defaultBranch: z.string(),
  githubOwner: z.string().nullable(),
  githubRepo: z.string().nullable(),
  isArchived: z.boolean(),
  startupScriptCommand: z.string().nullable(),
  startupScriptPath: z.string().nullable(),
  startupScriptTimeout: z.number(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

// Schema v1 - for importing legacy backups
const exportedWorkspaceSchemaV1 = z.object({
  id: z.string(),
  projectId: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  status: WorkspaceStatus,
  worktreePath: z.string().nullable(),
  branchName: z.string().nullable(),
  // Optional for backward compatibility with pre-Phase-3 backups
  isAutoGeneratedBranch: z.boolean().optional(),
  creationSource: WorkspaceCreationSource.optional(),
  creationMetadata: z.unknown().nullable().optional(),
  initErrorMessage: z.string().nullable(),
  initOutput: z.string().nullable(),
  initStartedAt: z.string().nullable(),
  initCompletedAt: z.string().nullable(),
  initRetryCount: z.number(),
  runScriptCommand: z.string().nullable(),
  runScriptCleanupCommand: z.string().nullable(),
  runScriptPid: z.number().nullable(),
  runScriptPort: z.number().nullable(),
  runScriptStartedAt: z.string().nullable(),
  // Accept both old SessionStatus and new RunScriptStatus values for backward compatibility
  runScriptStatus: z.union([RunScriptStatus, z.literal('PAUSED')]),
  prUrl: z.string().nullable(),
  githubIssueNumber: z.number().nullable(),
  githubIssueUrl: z.string().nullable(),
  prNumber: z.number().nullable(),
  prState: PRState,
  prReviewState: z.string().nullable(),
  prCiStatus: CIStatus,
  prUpdatedAt: z.string().nullable(),
  prCiFailedAt: z.string().nullable(),
  prCiLastNotifiedAt: z.string().nullable(),
  hasHadSessions: z.boolean(),
  cachedKanbanColumn: KanbanColumn,
  stateComputedAt: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

// Schema v2 - includes all Phase 3 and Phase 4 fields
const exportedWorkspaceSchemaV2 = exportedWorkspaceSchemaV1.extend({
  // PR review tracking (Phase 3+)
  prReviewLastCheckedAt: z.string().nullable(),
  prReviewLastCommentId: z.string().nullable(),
  // Ratchet tracking fields (Phase 3+)
  ratchetEnabled: z.boolean(),
  ratchetState: RatchetState,
  ratchetLastCheckedAt: z.string().nullable(),
  ratchetLastPushAt: z.string().nullable(),
  ratchetActiveSessionId: z.string().nullable(),
  ratchetLastCiRunId: z.string().nullable(),
  ratchetLastNotifiedState: RatchetState.nullable(),
});

const exportedClaudeSessionSchema = z.object({
  id: z.string(),
  workspaceId: z.string(),
  name: z.string().nullable(),
  workflow: z.string(),
  model: z.string(),
  status: SessionStatus,
  claudeSessionId: z.string().nullable(),
  claudeProcessPid: z.number().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const exportedTerminalSessionSchema = z.object({
  id: z.string(),
  workspaceId: z.string(),
  name: z.string().nullable(),
  status: SessionStatus,
  pid: z.number().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

// Schema v1 - for importing legacy backups
const exportedUserSettingsSchemaV1 = z.object({
  preferredIde: z.string(),
  customIdeCommand: z.string().nullable(),
  playSoundOnComplete: z.boolean(),
  notificationSoundPath: z.string().nullable(),
  // Deprecated fields - kept for backward compatibility during import
  autoFixCiIssues: z.boolean().optional(),
  autoFixPrReviewComments: z.boolean().optional(),
  prReviewFixAllowedUsers: z.array(z.string()).nullable().optional(),
  prReviewFixPrompt: z.string().nullable().optional(),
});

// Schema v2 - includes ratchet settings
const exportedUserSettingsSchemaV2 = z.object({
  preferredIde: z.string(),
  customIdeCommand: z.string().nullable(),
  playSoundOnComplete: z.boolean(),
  notificationSoundPath: z.string().nullable(),
  // Note: workspaceOrder and cachedSlashCommands are intentionally excluded as they are
  // rebuild-able cache data (per design doc: "Excludes cached data")
  // Ratchet settings (Phase 3+)
  ratchetEnabled: z.boolean(),
  ratchetAutoFixCi: z.boolean(),
  ratchetAutoFixReviews: z.boolean(),
  // Removed fields - kept for backward compatibility during import
  ratchetAutoFixConflicts: z.boolean().optional(),
  ratchetAutoMerge: z.boolean(),
  ratchetAllowedReviewers: z.unknown().nullish(), // JSON field - allow undefined from DB
  // Deprecated fields - kept for backward compatibility during import
  autoFixCiIssues: z.boolean().optional(),
  autoFixPrReviewComments: z.boolean().optional(),
  prReviewFixAllowedUsers: z.array(z.string()).nullable().optional(),
  prReviewFixPrompt: z.string().nullable().optional(),
});

// Schema v1 - for importing legacy backups
const exportDataSchemaV1 = z.object({
  meta: z.object({
    exportedAt: z.string(),
    version: z.string(),
    schemaVersion: z.literal(1),
  }),
  data: z.object({
    projects: z.array(exportedProjectSchema),
    workspaces: z.array(exportedWorkspaceSchemaV1),
    claudeSessions: z.array(exportedClaudeSessionSchema),
    terminalSessions: z.array(exportedTerminalSessionSchema),
    userSettings: exportedUserSettingsSchemaV1.nullable(),
  }),
});

// Schema v2 - includes all Phase 3 and Phase 4 fields
const exportDataSchemaV2 = z.object({
  meta: z.object({
    exportedAt: z.string(),
    version: z.string(),
    schemaVersion: z.literal(2),
  }),
  data: z.object({
    projects: z.array(exportedProjectSchema),
    workspaces: z.array(exportedWorkspaceSchemaV2),
    claudeSessions: z.array(exportedClaudeSessionSchema),
    terminalSessions: z.array(exportedTerminalSessionSchema),
    userSettings: exportedUserSettingsSchemaV2.nullable(),
  }),
});

// Main export schema that accepts both v1 and v2
export const exportDataSchema = z.union([exportDataSchemaV2, exportDataSchemaV1]);

export type ExportData = z.infer<typeof exportDataSchemaV2>;
export type ExportDataV1 = z.infer<typeof exportDataSchemaV1>;
export type ExportDataV2 = z.infer<typeof exportDataSchemaV2>;
