import type { inferRouterOutputs } from '@trpc/server';
import type { AppRouter } from '@/client/lib/trpc';
import type { WorkspaceSnapshotEntry } from '@/shared/workspace-snapshot';

type RouterOutputs = inferRouterOutputs<AppRouter>;

export type SidebarWorkspace =
  RouterOutputs['workspace']['getProjectSummaryState']['workspaces'][number];
export type KanbanWorkspace = RouterOutputs['workspace']['listWithKanbanState'][number];
export type WorkspaceDetail = RouterOutputs['workspace']['get'];

type SidebarSnapshotWorkspace = SidebarWorkspace & {
  sessionSummaries: WorkspaceSnapshotEntry['sessionSummaries'];
  snapshotComputedAt: string;
};

function projectSnapshotToCommonWorkspace(entry: WorkspaceSnapshotEntry) {
  return {
    id: entry.workspaceId,
    name: entry.name,
    createdAt: new Date(entry.createdAt),
    branchName: entry.branchName,
    prUrl: entry.prUrl,
    prNumber: entry.prNumber,
    prState: entry.prState,
    prCiStatus: entry.prCiStatus,
    ratchetEnabled: entry.ratchetEnabled,
    ratchetState: entry.ratchetState,
    runScriptStatus: entry.runScriptStatus,
    pendingRequestType: entry.pendingRequestType,
    ratchetButtonAnimated: entry.ratchetButtonAnimated,
    flowPhase: entry.flowPhase,
    ciObservation: entry.ciObservation,
    statusReason: entry.statusReason,
  };
}

export function projectSnapshotToSidebarWorkspace(
  entry: WorkspaceSnapshotEntry,
  existing?: SidebarWorkspace
): SidebarSnapshotWorkspace {
  return {
    githubIssueNumber: null,
    githubIssueUrl: null,
    linearIssueId: null,
    linearIssueIdentifier: null,
    linearIssueUrl: null,
    creationSource: 'MANUAL',
    stateComputedAt: null,
    ...existing,
    ...projectSnapshotToCommonWorkspace(entry),
    isWorking: entry.isWorking,
    sessionSummaries: entry.sessionSummaries,
    gitStats: entry.gitStats,
    lastActivityAt: entry.lastActivityAt,
    sidebarStatus: entry.sidebarStatus,
    cachedKanbanColumn: entry.kanbanColumn,
    snapshotComputedAt: entry.computedAt,
  };
}

function newKanbanWorkspaceDefaults(entry: WorkspaceSnapshotEntry): KanbanWorkspace {
  const createdAt = new Date(entry.createdAt);

  return {
    id: entry.workspaceId,
    projectId: entry.projectId,
    name: entry.name,
    description: null,
    status: entry.status,
    worktreePath: null,
    branchName: entry.branchName,
    isAutoGeneratedBranch: false,
    creationSource: 'MANUAL',
    creationMetadata: null,
    initErrorMessage: null,
    initOutput: null,
    initStartedAt: null,
    initCompletedAt: null,
    initScriptPid: null,
    initRetryCount: 0,
    runScriptCommand: null,
    runScriptPostRunCommand: null,
    runScriptCleanupCommand: null,
    runScriptPid: null,
    runScriptPort: null,
    runScriptStartedAt: null,
    runScriptStatus: entry.runScriptStatus,
    prUrl: entry.prUrl,
    githubIssueNumber: null,
    githubIssueUrl: null,
    linearIssueId: null,
    linearIssueIdentifier: null,
    linearIssueUrl: null,
    defaultSessionProvider: 'WORKSPACE_DEFAULT',
    ratchetSessionProvider: 'WORKSPACE_DEFAULT',
    createdAt,
    updatedAt: createdAt,
    prNumber: entry.prNumber,
    prState: entry.prState,
    prReviewState: null,
    prCiStatus: entry.prCiStatus,
    prUpdatedAt: null,
    prCiFailedAt: null,
    prCiLastNotifiedAt: null,
    prReviewLastCheckedAt: null,
    prReviewLastCommentId: null,
    ratchetEnabled: entry.ratchetEnabled,
    ratchetState: entry.ratchetState,
    ratchetLastCheckedAt: null,
    ratchetActiveSessionId: null,
    ratchetLastCiRunId: null,
    ratchetDispatchOutcome: null,
    ratchetDispatchRetryCount: 0,
    hasHadSessions: entry.hasHadSessions,
    cachedKanbanColumn: entry.kanbanColumn ?? 'WAITING',
    stateComputedAt: null,
    mode: 'STANDARD',
    autoIterationStatus: null,
    autoIterationConfig: null,
    autoIterationProgress: null,
    autoIterationSessionId: null,
    periodicTaskId: null,
    parentWorkspaceId: null,
    agentSessions: [],
    terminalSessions: [],
    kanbanColumn: entry.kanbanColumn,
    isWorking: entry.isWorking,
    ratchetButtonAnimated: entry.ratchetButtonAnimated,
    flowPhase: entry.flowPhase,
    ciObservation: entry.ciObservation,
    statusReason: entry.statusReason,
    isArchived: false,
    pendingRequestType: entry.pendingRequestType,
  };
}

export function projectSnapshotToKanbanWorkspace(
  entry: WorkspaceSnapshotEntry,
  existing?: KanbanWorkspace
): KanbanWorkspace {
  return {
    ...newKanbanWorkspaceDefaults(entry),
    ...existing,
    ...projectSnapshotToCommonWorkspace(entry),
    projectId: entry.projectId,
    status: entry.status,
    hasHadSessions: entry.hasHadSessions,
    cachedKanbanColumn: entry.kanbanColumn ?? existing?.cachedKanbanColumn ?? 'WAITING',
    kanbanColumn: entry.kanbanColumn,
    isWorking: entry.isWorking,
    isArchived: false,
  };
}

export function mergeProjectSnapshotIntoWorkspaceDetail(
  entry: WorkspaceSnapshotEntry,
  existing: WorkspaceDetail | undefined
): WorkspaceDetail | undefined {
  if (!existing) {
    return undefined;
  }

  return {
    ...existing,
    ...projectSnapshotToCommonWorkspace(entry),
    status: entry.status,
    hasHadSessions: entry.hasHadSessions,
    cachedKanbanColumn: entry.kanbanColumn ?? existing.cachedKanbanColumn,
    sessionSummaries: entry.sessionSummaries,
    sidebarStatus: entry.sidebarStatus,
  };
}
