-- Move the ratchet's seven columns off "Workspace" into a 1:1 "WorkspaceRatchet"
-- table. Every value is carried over by the backfill below, so no ratchet state
-- is lost: the columns named in Prisma's generated warning are read before the
-- table is redefined.
--
-- "ratchetLastCiRunId" is renamed to "dispatchSnapshotKey", which is what the
-- code writing it has always stored (PR number + CI signature + review activity
-- + merge conflict). The old name was kept only to avoid this migration.
-- CreateTable
CREATE TABLE "WorkspaceRatchet" (
    "workspaceId" TEXT NOT NULL PRIMARY KEY,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "state" TEXT NOT NULL DEFAULT 'IDLE',
    "lastCheckedAt" DATETIME,
    "activeSessionId" TEXT,
    "dispatchSnapshotKey" TEXT,
    "dispatchOutcome" TEXT,
    "dispatchRetryCount" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "WorkspaceRatchet_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Backfill one row per existing workspace before the columns go away.
INSERT INTO "WorkspaceRatchet" ("workspaceId", "enabled", "state", "lastCheckedAt", "activeSessionId", "dispatchSnapshotKey", "dispatchOutcome", "dispatchRetryCount")
SELECT "id", "ratchetEnabled", "ratchetState", "ratchetLastCheckedAt", "ratchetActiveSessionId", "ratchetLastCiRunId", "ratchetDispatchOutcome", "ratchetDispatchRetryCount"
FROM "Workspace";

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Workspace" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "worktreePath" TEXT,
    "branchName" TEXT,
    "isAutoGeneratedBranch" BOOLEAN NOT NULL DEFAULT false,
    "creationSource" TEXT NOT NULL DEFAULT 'MANUAL',
    "creationMetadata" JSONB,
    "initErrorMessage" TEXT,
    "initOutput" TEXT,
    "initStartedAt" DATETIME,
    "initCompletedAt" DATETIME,
    "initScriptPid" INTEGER,
    "initRetryCount" INTEGER NOT NULL DEFAULT 0,
    "runScriptCommand" TEXT,
    "runScriptPostRunCommand" TEXT,
    "runScriptCleanupCommand" TEXT,
    "runScriptPid" INTEGER,
    "runScriptPort" INTEGER,
    "runScriptStartedAt" DATETIME,
    "runScriptStatus" TEXT NOT NULL DEFAULT 'IDLE',
    "prUrl" TEXT,
    "githubIssueNumber" INTEGER,
    "githubIssueUrl" TEXT,
    "linearIssueId" TEXT,
    "linearIssueIdentifier" TEXT,
    "linearIssueUrl" TEXT,
    "defaultSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "ratchetSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "prNumber" INTEGER,
    "prState" TEXT NOT NULL DEFAULT 'NONE',
    "prReviewState" TEXT,
    "prCiStatus" TEXT NOT NULL DEFAULT 'UNKNOWN',
    "prUpdatedAt" DATETIME,
    "prDiscoveryLastCheckedAt" DATETIME,
    "prDiscoveryRetryCount" INTEGER NOT NULL DEFAULT 0,
    "prDiscoveryNextCheckAt" DATETIME,
    "prCiFailedAt" DATETIME,
    "prCiLastNotifiedAt" DATETIME,
    "prReviewLastCheckedAt" DATETIME,
    "prReviewLastCommentId" TEXT,
    "mode" TEXT NOT NULL DEFAULT 'STANDARD',
    "autoIterationStatus" TEXT,
    "autoIterationConfig" JSONB,
    "autoIterationProgress" JSONB,
    "autoIterationSessionId" TEXT,
    "periodicTaskId" TEXT,
    "parent_workspace_id" TEXT,
    "hasHadSessions" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "Workspace_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Workspace_periodicTaskId_fkey" FOREIGN KEY ("periodicTaskId") REFERENCES "PeriodicTask" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Workspace_parent_workspace_id_fkey" FOREIGN KEY ("parent_workspace_id") REFERENCES "Workspace" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Workspace" ("autoIterationConfig", "autoIterationProgress", "autoIterationSessionId", "autoIterationStatus", "branchName", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initScriptPid", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "mode", "name", "parent_workspace_id", "periodicTaskId", "prCiFailedAt", "prCiLastNotifiedAt", "prCiStatus", "prDiscoveryLastCheckedAt", "prDiscoveryNextCheckAt", "prDiscoveryRetryCount", "prNumber", "prReviewLastCheckedAt", "prReviewLastCommentId", "prReviewState", "prState", "prUpdatedAt", "prUrl", "projectId", "ratchetSessionProvider", "runScriptCleanupCommand", "runScriptCommand", "runScriptPid", "runScriptPort", "runScriptPostRunCommand", "runScriptStartedAt", "runScriptStatus", "status", "updatedAt", "worktreePath") SELECT "autoIterationConfig", "autoIterationProgress", "autoIterationSessionId", "autoIterationStatus", "branchName", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initScriptPid", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "mode", "name", "parent_workspace_id", "periodicTaskId", "prCiFailedAt", "prCiLastNotifiedAt", "prCiStatus", "prDiscoveryLastCheckedAt", "prDiscoveryNextCheckAt", "prDiscoveryRetryCount", "prNumber", "prReviewLastCheckedAt", "prReviewLastCommentId", "prReviewState", "prState", "prUpdatedAt", "prUrl", "projectId", "ratchetSessionProvider", "runScriptCleanupCommand", "runScriptCommand", "runScriptPid", "runScriptPort", "runScriptPostRunCommand", "runScriptStartedAt", "runScriptStatus", "status", "updatedAt", "worktreePath" FROM "Workspace";
DROP TABLE "Workspace";
ALTER TABLE "new_Workspace" RENAME TO "Workspace";
CREATE INDEX "Workspace_projectId_idx" ON "Workspace"("projectId");
CREATE INDEX "Workspace_status_idx" ON "Workspace"("status");
CREATE INDEX "Workspace_parent_workspace_id_idx" ON "Workspace"("parent_workspace_id");
CREATE INDEX "Workspace_projectId_status_idx" ON "Workspace"("projectId", "status");
CREATE INDEX "Workspace_projectId_updatedAt_idx" ON "Workspace"("projectId", "updatedAt");
CREATE INDEX "Workspace_projectId_createdAt_idx" ON "Workspace"("projectId", "createdAt");
CREATE INDEX "Workspace_status_prUrl_idx" ON "Workspace"("status", "prUrl");
CREATE INDEX "Workspace_status_prUrl_prDiscoveryNextCheckAt_idx" ON "Workspace"("status", "prUrl", "prDiscoveryNextCheckAt");
CREATE INDEX "Workspace_status_prUpdatedAt_idx" ON "Workspace"("status", "prUpdatedAt");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE INDEX "WorkspaceRatchet_enabled_state_idx" ON "WorkspaceRatchet"("enabled", "state");

-- CreateIndex
CREATE INDEX "WorkspaceRatchet_lastCheckedAt_idx" ON "WorkspaceRatchet"("lastCheckedAt");

-- Recreate the depth-1 triggers from 20260622135100_add_child_workspaces.
-- SQLite drops triggers together with the table they are attached to, so the
-- RedefineTables block above silently removed them. Any future migration that
-- redefines "Workspace" must recreate these triggers the same way.
CREATE TRIGGER enforce_workspace_depth_1
BEFORE INSERT ON "Workspace"
WHEN NEW."parent_workspace_id" IS NOT NULL
BEGIN
  -- Block self-parenting
  SELECT RAISE(ABORT, 'A workspace cannot be its own parent')
  WHERE NEW."id" = NEW."parent_workspace_id";
  -- Block grandchild chains: proposed parent must not already have a parent
  SELECT RAISE(ABORT, 'Child workspaces cannot have children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "id" = NEW."parent_workspace_id"
    AND "parent_workspace_id" IS NOT NULL
  );
END;

CREATE TRIGGER enforce_workspace_depth_1_update
BEFORE UPDATE ON "Workspace"
WHEN NEW."parent_workspace_id" IS NOT NULL
BEGIN
  -- Block self-parenting
  SELECT RAISE(ABORT, 'A workspace cannot be its own parent')
  WHERE NEW."id" = NEW."parent_workspace_id";
  -- Block grandchild chains: proposed parent must not already have a parent
  SELECT RAISE(ABORT, 'Child workspaces cannot have children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "id" = NEW."parent_workspace_id"
    AND "parent_workspace_id" IS NOT NULL
  );
  -- Block re-parenting a workspace that already has children
  SELECT RAISE(ABORT, 'Cannot re-parent a workspace that already has children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "parent_workspace_id" = NEW."id"
  );
END;
