import type {
  CIStatus,
  KanbanColumn,
  PRState,
  RatchetState,
  RunScriptStatus,
  WorkspaceCreationSource,
  WorkspaceStatus,
} from '../types/enums.js';

/** Flat workspace record -- no Prisma relations */
export interface WorkspaceRecord {
  id: string;
  projectId: string;
  name: string;
  description: string | null;
  status: WorkspaceStatus;
  branchName: string | null;
  isAutoGeneratedBranch: boolean;
  worktreePath: string | null;
  prUrl: string | null;
  prNumber: number | null;
  prState: PRState;
  prReviewState: string | null;
  prCiStatus: CIStatus;
  prUpdatedAt: Date | null;
  prCiFailedAt: Date | null;
  prCiLastNotifiedAt: Date | null;
  prReviewLastCheckedAt: Date | null;
  prReviewLastCommentId: string | null;
  ratchetEnabled: boolean;
  ratchetState: RatchetState;
  ratchetLastCheckedAt: Date | null;
  ratchetLastPushAt: Date | null;
  ratchetActiveSessionId: string | null;
  ratchetLastCiRunId: string | null;
  runScriptStatus: RunScriptStatus;
  hasHadSessions: boolean;
  cachedKanbanColumn: KanbanColumn;
  githubIssueNumber: number | null;
  githubIssueUrl: string | null;
  creationSource: WorkspaceCreationSource;
  createdAt: Date;
  updatedAt: Date;
}

export interface WorkspaceStorage {
  findRawById(id: string): Promise<WorkspaceRecord | null>;
  findRawByIdOrThrow(id: string): Promise<WorkspaceRecord>;
  update(id: string, data: Partial<WorkspaceRecord>): Promise<WorkspaceRecord>;
  transitionWithCas(
    id: string,
    fromStatus: WorkspaceStatus,
    data: Partial<WorkspaceRecord>
  ): Promise<{ count: number }>;
  markHasHadSessions(id: string): Promise<void>;
  clearRatchetActiveSession(workspaceId: string, sessionId: string): Promise<void>;
  findWithPRsForRatchet(): Promise<RatchetWorkspaceView[]>;
  findForRatchetById(id: string): Promise<RatchetWorkspaceView | null>;
  findWithPRsForCIMonitoring(): Promise<CIMonitoringView[]>;
  findWithPRsForReviewMonitoring(): Promise<ReviewMonitoringView[]>;
}

/** Projection for ratchet polling */
export interface RatchetWorkspaceView {
  id: string;
  prUrl: string;
  prNumber: number | null;
  prState: PRState;
  prCiStatus: CIStatus;
  ratchetEnabled: boolean;
  ratchetState: RatchetState;
  ratchetActiveSessionId: string | null;
  ratchetLastCiRunId: string | null;
  prReviewLastCheckedAt: Date | null;
}

/** Projection for CI monitoring */
export interface CIMonitoringView {
  id: string;
  prUrl: string;
  prCiStatus: CIStatus;
  prCiFailedAt: Date | null;
  prCiLastNotifiedAt: Date | null;
}

/** Projection for review monitoring */
export interface ReviewMonitoringView {
  id: string;
  prUrl: string;
  prNumber: number;
  prReviewLastCheckedAt: Date | null;
  prReviewLastCommentId: string | null;
}
