/**
 * Shared auto-generated branch rename routine.
 *
 * The branch-naming interceptor renames a workspace's auto-generated branch
 * to a meaningful one at the last safe moment before it becomes visible to
 * anyone else: on `gh pr create` or `git push`.
 *
 * The rename itself is identical in both — the once-per-workspace guard, the
 * `git branch -m`, persisting the new name, and unwinding the guard on every
 * failure path so a later attempt can retry. That logic lives here so it has
 * one definition; the interceptor supplies the trigger-specific labels and
 * follow-up work.
 */

import { gitCommand } from '@/backend/lib/shell';
import type { createLogger } from '@/backend/services/logger.service';
import { projectManagementService, workspaceDataService } from '@/backend/services/workspace';
import { workspaceGitStateService } from '@/backend/services/workspace-git-state.service';
import { generateBranchName } from './branch-rename.utils';
import type { InterceptorContext } from './types';

type Logger = ReturnType<typeof createLogger>;

export interface AutoBranchRename {
  /** Empty string when the workspace had no branch name recorded. */
  oldBranchName: string;
  newBranchName: string;
}

export interface AutoBranchRenameLabels {
  /** Command that triggered the rename, e.g. `gh pr create`. */
  detected: string;
  /** Event the rename precedes, e.g. `PR creation`. */
  before: string;
  /** Interceptor name, used in the catch-all error log. */
  interceptor: string;
}

/**
 * Renames auto-generated workspace branches, at most once per workspace.
 *
 * A workspace is claimed before the first await so parallel tool calls in the
 * same turn cannot both rename it. The claim is kept only once the workspace
 * needs no further attention — the rename landed, or the branch already had
 * the name we would have chosen — and released otherwise so a later trigger
 * can retry.
 */
export class AutoGeneratedBranchRenamer {
  private readonly renamedWorkspaces = new Set<string>();

  /** Drop tracked state so nothing leaks across a server restart. */
  reset(): void {
    this.renamedWorkspaces.clear();
  }

  /**
   * Rename the workspace's branch when it is still auto-generated.
   *
   * Returns the rename when one was performed and persisted, or null when
   * nothing needed doing (already renamed, branch not auto-generated, name
   * unchanged) or the attempt failed. Never throws: failures are logged and
   * reported as null, because interceptors must not break tool execution.
   */
  async renameIfAutoGenerated(
    context: InterceptorContext,
    labels: AutoBranchRenameLabels,
    logger: Logger
  ): Promise<AutoBranchRename | null> {
    if (this.renamedWorkspaces.has(context.workspaceId)) {
      return null;
    }

    // Claim the workspace before the first await. Parallel tool calls in the
    // same turn are interleaved at every suspension point, so a claim taken
    // after an await would let both callers pass the check above and rename.
    this.renamedWorkspaces.add(context.workspaceId);

    // Two paths keep the claim, so no later trigger re-checks this workspace:
    // a rename landed, or the branch already had the name we would have chosen.
    // Every other path — including errors — releases it in `finally` so a
    // later trigger can retry.
    let keepClaim = false;
    try {
      const workspace = await workspaceDataService.findById(context.workspaceId);
      if (!workspace?.isAutoGeneratedBranch) {
        return null;
      }

      const oldBranchName = workspace.branchName ?? '';
      logger.info(`Detected ${labels.detected} with auto-generated branch, renaming`, {
        workspaceId: context.workspaceId,
        currentBranch: oldBranchName,
      });

      const project = await projectManagementService.findById(workspace.projectId);
      const newBranchName = generateBranchName({
        branchPrefix: project?.githubOwner ?? '',
        workspaceName: workspace.name,
      });

      if (!newBranchName) {
        logger.warn('Could not generate branch name from workspace context', {
          workspaceId: context.workspaceId,
          workspaceName: workspace.name,
        });
        return null;
      }

      if (newBranchName === oldBranchName) {
        // Already the name we would pick; keep the claim so we do not re-check.
        await workspaceDataService.clearAutoGeneratedBranch(context.workspaceId);
        keepClaim = true;
        return null;
      }

      const result = await gitCommand(['branch', '-m', newBranchName], context.workingDir);
      workspaceGitStateService.invalidate(context.workingDir);
      if (result.code !== 0) {
        logger.warn(`Failed to rename branch before ${labels.before}`, {
          workspaceId: context.workspaceId,
          newBranchName,
          stderr: result.stderr,
        });
        return null;
      }

      // Persist the new name and clear the auto-generated flag
      await workspaceDataService.setBranchNameAndClearAutoGenerated(
        context.workspaceId,
        newBranchName
      );
      keepClaim = true;

      logger.info(`Renamed branch before ${labels.before}`, {
        workspaceId: context.workspaceId,
        oldBranch: oldBranchName,
        newBranch: newBranchName,
      });

      return { oldBranchName, newBranchName };
    } catch (error) {
      logger.error(`Error in ${labels.interceptor} interceptor`, {
        workspaceId: context.workspaceId,
        error,
      });
      return null;
    } finally {
      if (!keepClaim) {
        this.renamedWorkspaces.delete(context.workspaceId);
      }
    }
  }
}
