import { beforeEach, describe, expect, it, vi } from 'vitest';

const mockSetBranchNameAndClearAutoGenerated = vi.hoisted(() => vi.fn());
const mockGitCommand = vi.hoisted(() => vi.fn());

vi.mock('@/backend/services/workspace', () => ({
  workspaceDataService: {
    setBranchNameAndClearAutoGenerated: (...args: unknown[]) =>
      mockSetBranchNameAndClearAutoGenerated(...args),
  },
}));

vi.mock('@/backend/lib/shell', () => ({
  gitCommand: (...args: unknown[]) => mockGitCommand(...args),
}));

vi.mock('@/backend/services/logger.service', () => ({
  createLogger: () => ({
    debug: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
}));

import { branchRenameInterceptor } from './branch-rename.interceptor';

describe('branchRenameInterceptor', () => {
  const context = {
    workspaceId: 'w1',
    workingDir: '/tmp/w1',
  } as never;

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('subscribes to all tool events so Codex command titles are dispatched', () => {
    expect(branchRenameInterceptor.tools).toBe('*');
  });

  it('ignores errored tool events and non-rename commands', async () => {
    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'Bash',
        output: { isError: true },
      } as never,
      context
    );

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'Bash',
        output: { isError: false },
        input: { command: 'git status' },
      } as never,
      context
    );

    expect(mockGitCommand).not.toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
  });

  it('updates workspace branch name and clears auto-generated flag after git branch -m', async () => {
    mockGitCommand.mockResolvedValue({ code: 0, stdout: 'new-branch\n', stderr: '' });

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'Bash',
        output: { isError: false },
        input: { command: 'git branch -m better-name' },
      } as never,
      context
    );

    expect(mockGitCommand).toHaveBeenCalledWith(['rev-parse', '--abbrev-ref', 'HEAD'], '/tmp/w1');
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledOnce();
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledWith('w1', 'new-branch');
  });

  it('detects git branch -m when Codex provides the command as the tool name', async () => {
    mockGitCommand.mockResolvedValue({ code: 0, stdout: 'codex-name\n', stderr: '' });

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'git branch -m codex-name',
        output: { isError: false },
        input: {},
      } as never,
      context
    );

    expect(mockGitCommand).toHaveBeenCalledWith(['rev-parse', '--abbrev-ref', 'HEAD'], '/tmp/w1');
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledWith('w1', 'codex-name');
  });

  it.each([
    'git status && git branch -m chained-name',
    'false || git branch -m chained-name',
    'git status; git branch -m chained-name',
    'git status\ngit branch -m chained-name',
  ])('detects a branch rename in a chained shell command: %s', async (toolName) => {
    mockGitCommand.mockResolvedValue({ code: 0, stdout: 'chained-name\n', stderr: '' });

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName,
        output: { isError: false },
        input: {},
      } as never,
      context
    );

    expect(mockGitCommand).toHaveBeenCalledWith(['rev-parse', '--abbrev-ref', 'HEAD'], '/tmp/w1');
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledWith('w1', 'chained-name');
  });

  it.each([
    'echo git branch -m codex-name',
    'echo "literal && git branch -m not-a-rename"',
    'rg -n "git branch -m" .',
    "rg -n '; git branch -m' .",
    'Search git branch -m',
  ])('ignores a non-rename tool title containing the command text: %s', async (toolName) => {
    await branchRenameInterceptor.onToolComplete!(
      {
        toolName,
        output: { isError: false },
        input: {},
      } as never,
      context
    );

    expect(mockGitCommand).not.toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
  });

  it('skips updates when branch lookup fails or returns empty branch', async () => {
    mockGitCommand.mockResolvedValueOnce({ code: 1, stdout: '', stderr: 'failed' });

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'Bash',
        output: { isError: false },
        input: { command: 'git branch -M force-name' },
      } as never,
      context
    );

    mockGitCommand.mockResolvedValueOnce({ code: 0, stdout: '   \n', stderr: '' });
    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'Bash',
        output: { isError: false },
        input: { command: 'git branch -M force-name' },
      } as never,
      context
    );

    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
  });
});
