/**
 * Branch Rename Interceptor
 *
 * Monitors Bash tool executions for `git branch -m` or `git branch -M` commands
 * and updates the workspace with the new branch name when detected.
 * Also updates the workspace name if it was auto-generated.
 */

import { workspaceDataService } from '@/backend/domains/workspace';
import { gitCommand } from '@/backend/lib/shell';
import { extractInputValue, isString } from '@/backend/schemas/tool-inputs.schema';
import { createLogger } from '@/backend/services/logger.service';
import type { InterceptorContext, ToolEvent, ToolInterceptor } from './types';

const logger = createLogger('branch-rename');

/**
 * Converts a branch name to a workspace title by:
 * - Removing any username prefix (e.g., "user/" or "user-name/")
 * - Replacing hyphens and underscores with spaces
 * - Capitalizing the first letter of each word
 */
function branchNameToWorkspaceTitle(branchName: string): string {
  // Remove prefix if present (everything before and including the last /)
  const withoutPrefix = branchName.includes('/')
    ? branchName.substring(branchName.lastIndexOf('/') + 1)
    : branchName;

  // Replace hyphens and underscores with spaces, capitalize words
  return withoutPrefix
    .replace(/[-_]/g, ' ')
    .split(' ')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

export const branchRenameInterceptor: ToolInterceptor = {
  name: 'branch-rename',
  tools: ['Bash'],

  async onToolComplete(event: ToolEvent, context: InterceptorContext): Promise<void> {
    // Skip if tool execution failed
    if (event.output?.isError) {
      return;
    }

    // Check if this was a `git branch -m` or `git branch -M` command (branch rename)
    // -m: rename branch, -M: force rename (overwrite if target exists)
    // Use regex to avoid false positives from strings containing "git branch -m"
    const command = extractInputValue(event.input, 'command', isString, 'Bash', logger);
    if (!(command && /\bgit\s+branch\s+-[mM]\b/.test(command))) {
      return;
    }

    logger.info('Detected git branch rename command', {
      workspaceId: context.workspaceId,
      command,
    });

    // Get the current branch name from the worktree
    const result = await gitCommand(['rev-parse', '--abbrev-ref', 'HEAD'], context.workingDir);
    if (result.code !== 0) {
      logger.warn('Failed to get current branch after rename', {
        workspaceId: context.workspaceId,
        stderr: result.stderr,
      });
      return;
    }

    const newBranchName = result.stdout.trim();
    if (!newBranchName) {
      logger.warn('Empty branch name returned after rename', {
        workspaceId: context.workspaceId,
      });
      return;
    }

    // Update the workspace with the new branch name
    await workspaceDataService.setBranchName(context.workspaceId, newBranchName);

    logger.info('Updated workspace with new branch name', {
      workspaceId: context.workspaceId,
      newBranchName,
    });

    // Also update the workspace name if it was auto-generated
    const workspace = await workspaceDataService.findById(context.workspaceId);
    if (workspace?.isAutoGeneratedName) {
      const newWorkspaceName = branchNameToWorkspaceTitle(newBranchName);
      await workspaceDataService.setWorkspaceName(context.workspaceId, newWorkspaceName);

      logger.info('Updated workspace with new title based on branch name', {
        workspaceId: context.workspaceId,
        oldName: workspace.name,
        newName: newWorkspaceName,
      });
    }
  },
};
