/**
 * Branch Rename Interceptor
 *
 * Monitors tool executions for `git branch -m` or `git branch -M` commands
 * and updates the workspace with the new branch name when detected.
 */

import { gitCommand } from '@/backend/lib/shell';
import { createLogger } from '@/backend/services/logger.service';
import { workspaceDataService } from '@/backend/services/workspace';
import { extractMatchingCommand } from './branch-rename.utils';
import type { InterceptorContext, ToolEvent, ToolInterceptor } from './types';

const logger = createLogger('branch-rename');
const GIT_BRANCH_RENAME_REGEX = /\bgit\s+branch\s+-[mM]\b/;

export const branchRenameInterceptor: ToolInterceptor = {
  name: 'branch-rename',
  tools: '*',

  async onToolComplete(event: ToolEvent, context: InterceptorContext): Promise<void> {
    // Skip if tool execution failed
    if (event.output?.isError) {
      return;
    }

    // Check if this was a `git branch -m` or `git branch -M` command (branch rename)
    // -m: rename branch, -M: force rename (overwrite if target exists)
    // Use regex to avoid false positives from strings containing "git branch -m"
    const command = extractMatchingCommand(event, GIT_BRANCH_RENAME_REGEX, logger);
    if (!command) {
      return;
    }

    logger.info('Detected git branch rename command', {
      workspaceId: context.workspaceId,
      command,
    });

    // Get the current branch name from the worktree
    const result = await gitCommand(['rev-parse', '--abbrev-ref', 'HEAD'], context.workingDir);
    if (result.code !== 0) {
      logger.warn('Failed to get current branch after rename', {
        workspaceId: context.workspaceId,
        stderr: result.stderr,
      });
      return;
    }

    const newBranchName = result.stdout.trim();
    if (!newBranchName) {
      logger.warn('Empty branch name returned after rename', {
        workspaceId: context.workspaceId,
      });
      return;
    }

    // Update the workspace with the new branch name and mark it as agent-chosen.
    await workspaceDataService.setBranchNameAndClearAutoGenerated(
      context.workspaceId,
      newBranchName
    );

    logger.info('Updated workspace with new branch name', {
      workspaceId: context.workspaceId,
      newBranchName,
    });
  },
};
