/**
 * Branch Naming Interceptor
 *
 * Routes manual branch renames, pre-push renames, and pre-PR renames from one
 * command scan while preserving each trigger's lifecycle-specific behavior.
 */

import { gitCommand } from '@/backend/lib/shell';
import { createLogger } from '@/backend/services/logger.service';
import { workspaceDataService } from '@/backend/services/workspace';
import { workspaceGitStateService } from '@/backend/services/workspace-git-state.service';
import { type AutoBranchRenameLabels, AutoGeneratedBranchRenamer } from './auto-branch-rename';
import { extractMatchingCommands } from './branch-rename.utils';
import type { InterceptorContext, ToolEvent, ToolInterceptor } from './types';

const logger = createLogger('branch-naming');
const GIT_BRANCH_RENAME_TEXT_REGEX = /\bgit\s+branch\s+-[mM]\b/;
const GIT_PUSH_REGEX = /\bgit\s+push\b/;
const GH_PR_CREATE_REGEX = /\bgh\s+pr\s+create\b/;
const BRANCH_NAMING_TEXT_REGEX = /\b(?:git\s+branch\s+-[mM]|git\s+push|gh\s+pr\s+create)\b/;
const GIT_BRANCH_RENAME_COMMAND_REGEX = /(?:^|&&|\|\||[;&|\n(])\s*git\s+branch\s+-[mM]\b/;
const SHELL_COMMAND_PAYLOAD_REGEX =
  /(?:^|&&|\|\||[;&|\n(])\s*(?:\/(?:usr\/)?bin\/)?(?:ba)?sh\s+-[A-Za-z]*c[A-Za-z]*\s+\uE000(\d+)\uE001/g;
const MAX_PENDING_TOOL_CALLS = 1000;

const PUSH_RENAME_LABELS: AutoBranchRenameLabels = {
  detected: 'git push',
  before: 'push',
  interceptor: 'pre-push rename',
};
const PR_RENAME_LABELS: AutoBranchRenameLabels = {
  detected: 'gh pr create',
  before: 'PR creation',
  interceptor: 'pre-PR rename',
};

interface MaskedShellCommand {
  command: string;
  quotedArguments: string[];
}

interface QuotedArgument {
  endIndex: number;
  value: string;
}

type RemoteCleanupCandidate = {
  oldBranchName: string;
  newBranchName: string;
  workspaceId: string;
  workingDir: string;
};

type PendingBranchNamingCall = {
  inputSnapshot: BranchNamingInputSnapshot;
  matches: BranchNamingMatch[];
  remoteCleanupCandidate?: RemoteCleanupCandidate;
};

type BranchNamingInputSnapshot = readonly [
  toolName: string,
  command: string | undefined,
  cmd: string | undefined,
  title: string | undefined,
];

type BranchNamingMatch = {
  command: string;
  handler: BranchNamingHandler;
};

type BranchNamingHandler = {
  name: 'manual-rename' | 'push' | 'pr-create';
  onStart?: (
    event: ToolEvent,
    context: InterceptorContext,
    pending: PendingBranchNamingCall,
    command: string
  ) => Promise<void>;
  onComplete?: (
    event: ToolEvent,
    context: InterceptorContext,
    pending: PendingBranchNamingCall,
    command: string
  ) => Promise<void>;
};

type BranchNamingRoute = readonly [regex: RegExp, handler: BranchNamingHandler];

function readQuotedArgument(command: string, startIndex: number): QuotedArgument {
  const quote = command.charAt(startIndex);
  let value = '';
  let endIndex = startIndex + 1;

  while (endIndex < command.length && command[endIndex] !== quote) {
    const character = command.charAt(endIndex);
    if (quote === '"' && character === '\\' && endIndex + 1 < command.length) {
      const escapedCharacter = command.charAt(endIndex + 1);
      if (escapedCharacter !== '\n') {
        value += /["\\$`]/.test(escapedCharacter) ? escapedCharacter : character + escapedCharacter;
      }
      endIndex += 2;
      continue;
    }
    value += character;
    endIndex += 1;
  }

  return { endIndex, value };
}

function findShellCommentEnd(command: string, startIndex: number): number {
  const newlineIndex = command.indexOf('\n', startIndex);
  return newlineIndex === -1 ? command.length : newlineIndex;
}

function maskQuotedArgumentsAndComments(command: string): MaskedShellCommand {
  let maskedCommand = '';
  const quotedArguments: string[] = [];
  let atWordStart = true;

  for (let index = 0; index < command.length; index += 1) {
    const character = command.charAt(index);

    if (character === '#' && atWordStart) {
      index = findShellCommentEnd(command, index);
      if (index < command.length) {
        maskedCommand += '\n';
      }
      atWordStart = true;
      continue;
    }

    if (character === "'" || character === '"') {
      const quotedArgument = readQuotedArgument(command, index);
      index = quotedArgument.endIndex;
      const quotedArgumentIndex = quotedArguments.push(quotedArgument.value) - 1;
      maskedCommand += `\uE000${quotedArgumentIndex}\uE001`;
      atWordStart = false;
      continue;
    }

    if (character === '\\' && index + 1 < command.length) {
      maskedCommand += '  ';
      index += 1;
      atWordStart = false;
      continue;
    }

    maskedCommand += character;
    atWordStart = /[\s;&|()]/.test(character);
  }

  return { command: maskedCommand, quotedArguments };
}

function containsGitBranchRenameCommand(command: string): boolean {
  const masked = maskQuotedArgumentsAndComments(command);
  if (GIT_BRANCH_RENAME_COMMAND_REGEX.test(masked.command)) {
    return true;
  }

  for (const match of masked.command.matchAll(SHELL_COMMAND_PAYLOAD_REGEX)) {
    const payload = masked.quotedArguments[Number(match[1])];
    if (payload !== undefined && containsGitBranchRenameCommand(payload)) {
      return true;
    }
  }

  return false;
}

function parseRemoteName(upstreamRef: string): string | undefined {
  const slashIndex = upstreamRef.indexOf('/');
  if (slashIndex <= 0) {
    return undefined;
  }
  return upstreamRef.slice(0, slashIndex);
}

function normalizeRemoteBranchName(branchName: string, remoteName: string): string {
  const remotePrefix = `${remoteName}/`;
  if (branchName.startsWith(remotePrefix)) {
    return branchName.slice(remotePrefix.length);
  }

  const fullRefPrefix = `refs/remotes/${remoteName}/`;
  if (branchName.startsWith(fullRefPrefix)) {
    return branchName.slice(fullRefPrefix.length);
  }

  return branchName;
}

async function getRefCommit(ref: string, workingDir: string): Promise<string | undefined> {
  const result = await gitCommand(['rev-parse', '--verify', '--quiet', ref], workingDir);
  if (result.code !== 0) {
    return undefined;
  }
  const commit = result.stdout.trim();
  return commit || undefined;
}

async function cleanupSupersededRemoteBranch(context: RemoteCleanupCandidate): Promise<void> {
  const headResult = await gitCommand(['rev-parse', 'HEAD'], context.workingDir);
  if (headResult.code !== 0) {
    logger.warn('Skipping remote branch cleanup; failed to resolve HEAD', {
      workspaceId: context.workspaceId,
      stderr: headResult.stderr,
    });
    return;
  }
  const headCommit = headResult.stdout.trim();
  if (!headCommit) {
    return;
  }

  const upstreamResult = await gitCommand(
    ['rev-parse', '--abbrev-ref', '--symbolic-full-name', '@{upstream}'],
    context.workingDir
  );
  if (upstreamResult.code !== 0) {
    return;
  }

  const upstreamRef = upstreamResult.stdout.trim();
  const remoteName = parseRemoteName(upstreamRef);
  if (!remoteName) {
    return;
  }

  const oldRemoteBranchName = normalizeRemoteBranchName(context.oldBranchName, remoteName);
  const newRemoteBranchName = normalizeRemoteBranchName(context.newBranchName, remoteName);
  if (!(oldRemoteBranchName && newRemoteBranchName)) {
    return;
  }
  if (oldRemoteBranchName === newRemoteBranchName) {
    return;
  }

  const oldRemoteRef = `refs/remotes/${remoteName}/${oldRemoteBranchName}`;
  const newRemoteRef = `refs/remotes/${remoteName}/${newRemoteBranchName}`;
  const oldRemoteCommit = await getRefCommit(oldRemoteRef, context.workingDir);
  const newRemoteCommit = await getRefCommit(newRemoteRef, context.workingDir);
  if (!(oldRemoteCommit && newRemoteCommit)) {
    return;
  }

  if (oldRemoteCommit !== headCommit || newRemoteCommit !== headCommit) {
    return;
  }

  const deleteResult = await gitCommand(
    ['push', remoteName, '--delete', oldRemoteBranchName],
    context.workingDir
  );
  workspaceGitStateService.invalidate(context.workingDir);
  if (deleteResult.code !== 0) {
    logger.warn('Failed to delete superseded remote branch', {
      workspaceId: context.workspaceId,
      oldBranchName: context.oldBranchName,
      remoteName,
      stderr: deleteResult.stderr,
    });
    return;
  }

  logger.info('Deleted superseded remote branch after pre-PR rename', {
    workspaceId: context.workspaceId,
    oldBranchName: context.oldBranchName,
    newBranchName: context.newBranchName,
    remoteName,
  });
}

function pendingCallKey(sessionId: string, toolUseId: string): string {
  return JSON.stringify([sessionId, toolUseId]);
}

function captureBranchNamingInput(event: ToolEvent): BranchNamingInputSnapshot {
  const stringValue = (value: unknown): string | undefined =>
    typeof value === 'string' ? value : undefined;

  return [
    event.toolName,
    stringValue(event.input.command),
    stringValue(event.input.cmd),
    stringValue(event.input.title),
  ];
}

function hasSameBranchNamingInput(snapshot: BranchNamingInputSnapshot, event: ToolEvent): boolean {
  const completedSnapshot = captureBranchNamingInput(event);
  return snapshot.every((value, index) => value === completedSnapshot[index]);
}

class BranchNamingInterceptor implements ToolInterceptor {
  readonly name = 'branch-naming';
  readonly tools = '*';

  private readonly renamer = new AutoGeneratedBranchRenamer();
  private readonly pendingCalls = new Map<string, PendingBranchNamingCall>();

  private readonly completeManualRename = async (
    event: ToolEvent,
    context: InterceptorContext,
    _pending: PendingBranchNamingCall,
    command: string
  ): Promise<void> => {
    if (!containsGitBranchRenameCommand(command)) {
      return;
    }

    workspaceGitStateService.invalidate(context.workingDir);
    if (event.output?.isError) {
      return;
    }

    logger.info('Detected git branch rename command', {
      workspaceId: context.workspaceId,
      command,
    });

    const result = await gitCommand(['rev-parse', '--abbrev-ref', 'HEAD'], context.workingDir);
    if (result.code !== 0) {
      logger.warn('Failed to get current branch after rename', {
        workspaceId: context.workspaceId,
        stderr: result.stderr,
      });
      return;
    }

    const newBranchName = result.stdout.trim();
    if (!newBranchName) {
      logger.warn('Empty branch name returned after rename', {
        workspaceId: context.workspaceId,
      });
      return;
    }

    await workspaceDataService.setBranchNameAndClearAutoGenerated(
      context.workspaceId,
      newBranchName
    );

    logger.info('Updated workspace with new branch name', {
      workspaceId: context.workspaceId,
      newBranchName,
    });
  };

  private readonly startPush = async (
    _event: ToolEvent,
    context: InterceptorContext
  ): Promise<void> => {
    await this.renamer.renameIfAutoGenerated(context, PUSH_RENAME_LABELS, logger);
  };

  private readonly completePush = async (
    event: ToolEvent,
    context: InterceptorContext
  ): Promise<void> => {
    if (event.output?.isError) {
      return;
    }

    try {
      await workspaceDataService.resetPRDiscoveryBackoff(context.workspaceId);
    } catch (error) {
      logger.error('Failed to reset PR discovery after git push', {
        workspaceId: context.workspaceId,
        sessionId: context.sessionId,
        toolUseId: event.toolUseId,
        error,
      });
    }
  };

  private readonly startPrCreate = async (
    _event: ToolEvent,
    context: InterceptorContext,
    pending: PendingBranchNamingCall
  ): Promise<void> => {
    const rename = await this.renamer.renameIfAutoGenerated(context, PR_RENAME_LABELS, logger);
    if (rename?.oldBranchName) {
      pending.remoteCleanupCandidate = {
        oldBranchName: rename.oldBranchName,
        newBranchName: rename.newBranchName,
        workspaceId: context.workspaceId,
        workingDir: context.workingDir,
      };
    }
  };

  private readonly completePrCreate = async (
    event: ToolEvent,
    _context: InterceptorContext,
    pending: PendingBranchNamingCall
  ): Promise<void> => {
    const candidate = pending.remoteCleanupCandidate;
    if (!candidate || event.output?.isError) {
      return;
    }

    try {
      await cleanupSupersededRemoteBranch(candidate);
    } catch (error) {
      logger.error('Error cleaning up superseded remote branch', {
        workspaceId: candidate.workspaceId,
        toolUseId: event.toolUseId,
        error,
      });
    }
  };

  private readonly manualRenameHandler: BranchNamingHandler = {
    name: 'manual-rename',
    onComplete: this.completeManualRename,
  };

  private readonly pushHandler: BranchNamingHandler = {
    name: 'push',
    onStart: this.startPush,
    onComplete: this.completePush,
  };

  private readonly prCreateHandler: BranchNamingHandler = {
    name: 'pr-create',
    onStart: this.startPrCreate,
    onComplete: this.completePrCreate,
  };

  private readonly routes: readonly BranchNamingRoute[] = [
    [GIT_BRANCH_RENAME_TEXT_REGEX, this.manualRenameHandler],
    [GH_PR_CREATE_REGEX, this.prCreateHandler],
    [GIT_PUSH_REGEX, this.pushHandler],
  ];

  private trackPendingCall(
    sessionId: string,
    toolUseId: string,
    pending: PendingBranchNamingCall
  ): void {
    const key = pendingCallKey(sessionId, toolUseId);
    if (this.pendingCalls.has(key)) {
      this.pendingCalls.delete(key);
    }

    while (this.pendingCalls.size >= MAX_PENDING_TOOL_CALLS) {
      const oldestKey = this.pendingCalls.keys().next().value;
      if (!oldestKey) {
        break;
      }
      this.pendingCalls.delete(oldestKey);
    }

    this.pendingCalls.set(key, pending);
  }

  private async runHandler(
    handler: BranchNamingHandler,
    phase: 'start' | 'complete',
    run: () => Promise<void> | undefined,
    event: ToolEvent,
    context: InterceptorContext
  ): Promise<void> {
    try {
      await run();
    } catch (error) {
      logger.error('Branch naming handler error', {
        handler: handler.name,
        phase,
        workspaceId: context.workspaceId,
        sessionId: context.sessionId,
        toolUseId: event.toolUseId,
        error,
      });
    }
  }

  private findManualRenameCommand(event: ToolEvent): string | undefined {
    return extractMatchingCommands(event, GIT_BRANCH_RENAME_TEXT_REGEX, logger).find(
      containsGitBranchRenameCommand
    );
  }

  start(): void {
    this.renamer.reset();
    this.pendingCalls.clear();
  }

  stop(): void {
    this.renamer.reset();
    this.pendingCalls.clear();
  }

  async onToolStart(event: ToolEvent, context: InterceptorContext): Promise<void> {
    const commands = extractMatchingCommands(event, BRANCH_NAMING_TEXT_REGEX, logger);
    if (commands.length === 0) {
      return;
    }

    const matches = this.routes.flatMap(([regex, handler]) => {
      const command = commands.find((candidate) => regex.test(candidate));
      return command ? [{ command, handler }] : [];
    });

    const pending = {
      inputSnapshot: captureBranchNamingInput(event),
      matches,
    };
    this.trackPendingCall(context.sessionId, event.toolUseId, pending);

    for (const match of matches) {
      await this.runHandler(
        match.handler,
        'start',
        () => match.handler.onStart?.(event, context, pending, match.command),
        event,
        context
      );
    }
  }

  async onToolComplete(event: ToolEvent, context: InterceptorContext): Promise<void> {
    const key = pendingCallKey(context.sessionId, event.toolUseId);
    const pending = this.pendingCalls.get(key);
    if (!pending) {
      const command = this.findManualRenameCommand(event);
      if (command) {
        const fallback = {
          inputSnapshot: captureBranchNamingInput(event),
          matches: [{ command, handler: this.manualRenameHandler }],
        };
        await this.runHandler(
          this.manualRenameHandler,
          'complete',
          () => this.completeManualRename(event, context, fallback, command),
          event,
          context
        );
      }
      return;
    }
    this.pendingCalls.delete(key);

    const hasManualRenameMatch = pending.matches.some(
      (match) => match.handler === this.manualRenameHandler
    );
    const shouldRescanManualRename =
      hasManualRenameMatch && !hasSameBranchNamingInput(pending.inputSnapshot, event);
    const completedManualRenameCommand = shouldRescanManualRename
      ? this.findManualRenameCommand(event)
      : undefined;

    for (const match of pending.matches) {
      let command = match.command;
      if (match.handler === this.manualRenameHandler && shouldRescanManualRename) {
        if (!completedManualRenameCommand) {
          continue;
        }
        command = completedManualRenameCommand;
      }
      await this.runHandler(
        match.handler,
        'complete',
        () => match.handler.onComplete?.(event, context, pending, command),
        event,
        context
      );
    }
  }
}

export function createBranchNamingInterceptor(): ToolInterceptor {
  return new BranchNamingInterceptor();
}

export const branchNamingInterceptor = createBranchNamingInterceptor();
