import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { InterceptorContext, ToolEvent } from './types';

const mockFindById = vi.fn();
const mockSetBranchName = vi.fn();
const mockFindProjectById = vi.fn();
const mockGitCommand = vi.fn();

vi.mock('@/backend/domains/workspace', () => ({
  workspaceDataService: {
    findById: (...args: unknown[]) => mockFindById(...args),
    setBranchName: (...args: unknown[]) => mockSetBranchName(...args),
  },
  projectManagementService: {
    findById: (...args: unknown[]) => mockFindProjectById(...args),
  },
}));

vi.mock('@/backend/lib/shell', () => ({
  gitCommand: (...args: unknown[]) => mockGitCommand(...args),
}));

vi.mock('@/backend/services/logger.service', () => ({
  createLogger: () => ({
    info: vi.fn(),
    debug: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
}));

// Import after mocks are set up
import { generateBranchName, prePrRenameInterceptor } from './pre-pr-rename.interceptor';

const context: InterceptorContext = {
  sessionId: 'session-1',
  workspaceId: 'workspace-1',
  workingDir: '/tmp/workspace',
  timestamp: new Date('2026-02-17T00:00:00.000Z'),
};

function createEvent(overrides: Partial<ToolEvent>): ToolEvent {
  return {
    toolUseId: 'tool-1',
    toolName: 'Bash',
    input: {},
    ...overrides,
  };
}

describe('prePrRenameInterceptor', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix authentication bug',
      branchName: 'adeeshaek/dolphin-1',
      isAutoGeneratedBranch: true,
      projectId: 'project-1',
    });
    mockFindProjectById.mockResolvedValue({
      id: 'project-1',
      githubOwner: 'adeeshaek',
    });
    mockGitCommand.mockResolvedValue({ code: 0, stdout: '', stderr: '' });
    mockSetBranchName.mockResolvedValue({});
  });

  it('renames branch when gh pr create detected and branch is auto-generated', async () => {
    const event = createEvent({
      input: { command: 'gh pr create --title "Fix auth bug"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-rename-1',
    });

    expect(mockGitCommand).toHaveBeenCalledWith(
      ['branch', '-m', 'adeeshaek/fix-authentication-bug'],
      '/tmp/workspace'
    );
    expect(mockSetBranchName).toHaveBeenCalledWith(
      'ws-rename-1',
      'adeeshaek/fix-authentication-bug',
      { clearAutoGenerated: true }
    );
  });

  it('skips when branch is not auto-generated', async () => {
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix auth',
      branchName: 'adeeshaek/fix-auth',
      isAutoGeneratedBranch: false,
      projectId: 'project-1',
    });

    const event = createEvent({
      input: { command: 'gh pr create --title "Fix auth"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-skip-not-auto',
    });

    expect(mockGitCommand).not.toHaveBeenCalled();
    expect(mockSetBranchName).not.toHaveBeenCalled();
  });

  it('skips when workspace not found', async () => {
    mockFindById.mockResolvedValue(null);

    const event = createEvent({
      input: { command: 'gh pr create --title "test"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-not-found',
    });

    expect(mockGitCommand).not.toHaveBeenCalled();
  });

  it('skips non-pr-create commands', async () => {
    const event = createEvent({
      input: { command: 'gh pr list' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-list-cmd',
    });

    expect(mockFindById).not.toHaveBeenCalled();
    expect(mockGitCommand).not.toHaveBeenCalled();
  });

  it('handles git rename failure gracefully', async () => {
    mockGitCommand.mockResolvedValue({
      code: 1,
      stdout: '',
      stderr: 'fatal: branch already exists',
    });

    const event = createEvent({
      input: { command: 'gh pr create --title "test"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-git-fail',
    });

    expect(mockGitCommand).toHaveBeenCalled();
    expect(mockSetBranchName).not.toHaveBeenCalled();
  });

  it('does not rename twice for the same workspace', async () => {
    const event = createEvent({
      input: { command: 'gh pr create --title "test"' },
    });

    const wsContext = { ...context, workspaceId: 'ws-dedup' };

    await prePrRenameInterceptor.onToolStart!(event, wsContext);
    await prePrRenameInterceptor.onToolStart!(event, wsContext);

    expect(mockGitCommand).toHaveBeenCalledTimes(1);
  });

  it('generates branch name without prefix when project has no githubOwner', async () => {
    mockFindProjectById.mockResolvedValue({ id: 'project-1', githubOwner: null });

    const event = createEvent({
      input: { command: 'gh pr create --title "test"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-no-prefix',
    });

    expect(mockGitCommand).toHaveBeenCalledWith(
      ['branch', '-m', 'fix-authentication-bug'],
      '/tmp/workspace'
    );
  });

  it('detects gh pr create in cmd field', async () => {
    const event = createEvent({
      toolName: 'exec_command',
      input: { cmd: 'gh pr create --title "test"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-cmd-field',
    });

    expect(mockGitCommand).toHaveBeenCalled();
  });
});

describe('generateBranchName', () => {
  it('kebab-cases workspace name with prefix', () => {
    expect(
      generateBranchName({
        branchPrefix: 'adeeshaek',
        workspaceName: 'Fix Authentication Bug',
      })
    ).toBe('adeeshaek/fix-authentication-bug');
  });

  it('kebab-cases without prefix', () => {
    expect(
      generateBranchName({
        branchPrefix: '',
        workspaceName: 'Add user login',
      })
    ).toBe('add-user-login');
  });

  it('truncates long names to 30 characters', () => {
    const result = generateBranchName({
      branchPrefix: '',
      workspaceName: 'This is a very long workspace name that should be truncated',
    });
    // The slug portion (without prefix) should be at most 30 chars
    expect(result.length).toBeLessThanOrEqual(30);
  });

  it('handles special characters', () => {
    expect(
      generateBranchName({
        branchPrefix: 'user',
        workspaceName: 'Fix: the @#$ weird (bug) [123]',
      })
    ).toBe('user/fix-the-weird-bug-123');
  });

  it('returns empty string for empty workspace name', () => {
    expect(
      generateBranchName({
        branchPrefix: 'user',
        workspaceName: '',
      })
    ).toBe('');
  });

  it('strips leading and trailing hyphens', () => {
    expect(
      generateBranchName({
        branchPrefix: '',
        workspaceName: '---hello world---',
      })
    ).toBe('hello-world');
  });
});
