/**
 * Pre-PR Branch Rename Interceptor
 *
 * Detects `gh pr create` on tool start and renames auto-generated branches
 * to meaningful names before the PR is created. Uses direct `git branch -m`
 * so the rename completes before the network-bound `gh pr create` executes.
 */

import { gitCommand } from '@/backend/lib/shell';
import { createLogger } from '@/backend/services/logger.service';
import { workspaceGitStateService } from '@/backend/services/workspace-git-state.service';
import { type AutoBranchRenameLabels, AutoGeneratedBranchRenamer } from './auto-branch-rename';
import { extractMatchingCommand, generateBranchName } from './branch-rename.utils';
import type { InterceptorContext, ToolEvent, ToolInterceptor } from './types';

const logger = createLogger('pre-pr-rename');
const GH_PR_CREATE_REGEX = /\bgh\s+pr\s+create\b/;
const MAX_REMOTE_CLEANUP_CANDIDATES = 1000;
const RENAME_LABELS: AutoBranchRenameLabels = {
  detected: 'gh pr create',
  before: 'PR creation',
  interceptor: 'pre-PR rename',
};

type RemoteCleanupCandidate = {
  oldBranchName: string;
  newBranchName: string;
  workspaceId: string;
  workingDir: string;
};

export { generateBranchName };

function parseRemoteName(upstreamRef: string): string | undefined {
  const slashIndex = upstreamRef.indexOf('/');
  if (slashIndex <= 0) {
    return undefined;
  }
  return upstreamRef.slice(0, slashIndex);
}

function normalizeRemoteBranchName(branchName: string, remoteName: string): string {
  const remotePrefix = `${remoteName}/`;
  if (branchName.startsWith(remotePrefix)) {
    return branchName.slice(remotePrefix.length);
  }

  const fullRefPrefix = `refs/remotes/${remoteName}/`;
  if (branchName.startsWith(fullRefPrefix)) {
    return branchName.slice(fullRefPrefix.length);
  }

  return branchName;
}

async function getRefCommit(ref: string, workingDir: string): Promise<string | undefined> {
  const result = await gitCommand(['rev-parse', '--verify', '--quiet', ref], workingDir);
  if (result.code !== 0) {
    return undefined;
  }
  const commit = result.stdout.trim();
  return commit || undefined;
}

async function cleanupSupersededRemoteBranch(context: {
  workspaceId: string;
  workingDir: string;
  oldBranchName: string;
  newBranchName: string;
}): Promise<void> {
  if (context.oldBranchName === context.newBranchName) {
    return;
  }

  const headResult = await gitCommand(['rev-parse', 'HEAD'], context.workingDir);
  if (headResult.code !== 0) {
    logger.warn('Skipping remote branch cleanup; failed to resolve HEAD', {
      workspaceId: context.workspaceId,
      stderr: headResult.stderr,
    });
    return;
  }
  const headCommit = headResult.stdout.trim();
  if (!headCommit) {
    return;
  }

  const upstreamResult = await gitCommand(
    ['rev-parse', '--abbrev-ref', '--symbolic-full-name', '@{upstream}'],
    context.workingDir
  );
  if (upstreamResult.code !== 0) {
    return;
  }

  const upstreamRef = upstreamResult.stdout.trim();
  const remoteName = parseRemoteName(upstreamRef);
  if (!remoteName) {
    return;
  }

  const oldRemoteBranchName = normalizeRemoteBranchName(context.oldBranchName, remoteName);
  const newRemoteBranchName = normalizeRemoteBranchName(context.newBranchName, remoteName);
  if (!(oldRemoteBranchName && newRemoteBranchName)) {
    return;
  }

  if (oldRemoteBranchName === newRemoteBranchName) {
    return;
  }

  const oldRemoteRef = `refs/remotes/${remoteName}/${oldRemoteBranchName}`;
  const newRemoteRef = `refs/remotes/${remoteName}/${newRemoteBranchName}`;

  const oldRemoteCommit = await getRefCommit(oldRemoteRef, context.workingDir);
  const newRemoteCommit = await getRefCommit(newRemoteRef, context.workingDir);
  if (!(oldRemoteCommit && newRemoteCommit)) {
    return;
  }

  // Delete the old remote branch only when both remote refs still point to HEAD.
  // This avoids deleting unexpected branch history if refs diverged.
  if (oldRemoteCommit !== headCommit || newRemoteCommit !== headCommit) {
    return;
  }

  const deleteResult = await gitCommand(
    ['push', remoteName, '--delete', oldRemoteBranchName],
    context.workingDir
  );
  workspaceGitStateService.invalidate(context.workingDir);
  if (deleteResult.code !== 0) {
    logger.warn('Failed to delete superseded remote branch', {
      workspaceId: context.workspaceId,
      oldBranchName: context.oldBranchName,
      remoteName,
      stderr: deleteResult.stderr,
    });
    return;
  }

  logger.info('Deleted superseded remote branch after pre-PR rename', {
    workspaceId: context.workspaceId,
    oldBranchName: context.oldBranchName,
    newBranchName: context.newBranchName,
    remoteName,
  });
}

class PrePrRenameInterceptor implements ToolInterceptor {
  readonly name = 'pre-pr-rename';
  readonly tools = '*';

  private readonly renamer = new AutoGeneratedBranchRenamer();
  private remoteCleanupCandidates = new Map<string, RemoteCleanupCandidate>();

  private setRemoteCleanupCandidate(toolUseId: string, candidate: RemoteCleanupCandidate): void {
    if (this.remoteCleanupCandidates.has(toolUseId)) {
      this.remoteCleanupCandidates.delete(toolUseId);
    }

    while (this.remoteCleanupCandidates.size >= MAX_REMOTE_CLEANUP_CANDIDATES) {
      const oldestToolUseId = this.remoteCleanupCandidates.keys().next().value;
      if (!oldestToolUseId) {
        break;
      }
      this.remoteCleanupCandidates.delete(oldestToolUseId);
    }

    this.remoteCleanupCandidates.set(toolUseId, candidate);
  }

  start(): void {
    // Ensure no stale state leaks across server restarts.
    this.renamer.reset();
    this.remoteCleanupCandidates.clear();
  }

  stop(): void {
    this.renamer.reset();
    this.remoteCleanupCandidates.clear();
  }

  async onToolStart(event: ToolEvent, context: InterceptorContext): Promise<void> {
    if (!extractMatchingCommand(event, GH_PR_CREATE_REGEX, logger)) {
      return;
    }

    const rename = await this.renamer.renameIfAutoGenerated(context, RENAME_LABELS, logger);
    if (rename?.oldBranchName) {
      this.setRemoteCleanupCandidate(event.toolUseId, {
        oldBranchName: rename.oldBranchName,
        newBranchName: rename.newBranchName,
        workspaceId: context.workspaceId,
        workingDir: context.workingDir,
      });
    }
  }

  async onToolComplete(event: ToolEvent): Promise<void> {
    const candidate = this.remoteCleanupCandidates.get(event.toolUseId);
    if (!candidate) {
      return;
    }
    this.remoteCleanupCandidates.delete(event.toolUseId);

    if (event.output?.isError) {
      return;
    }

    try {
      await cleanupSupersededRemoteBranch(candidate);
    } catch (error) {
      logger.error('Error cleaning up superseded remote branch', {
        workspaceId: candidate.workspaceId,
        toolUseId: event.toolUseId,
        error,
      });
    }
  }
}

export function createPrePrRenameInterceptor(): ToolInterceptor {
  return new PrePrRenameInterceptor();
}

export const prePrRenameInterceptor = createPrePrRenameInterceptor();
