import type { UserSettings, Workspace } from '@prisma-gen/client';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import * as gitOpsServiceModule from '@/backend/services/git-ops.service';
import type { createLogger } from '@/backend/services/logger.service';
import * as userSettingsAccessorModule from '@/backend/services/settings';
import * as projectAccessorModule from '@/backend/services/workspace/resources/project.accessor';
import * as workspaceAccessorModule from '@/backend/services/workspace/resources/workspace.accessor';
import * as worktreeLifecycleServiceModule from '@/backend/services/workspace/service/worktree/worktree-lifecycle.service';
import { unsafeCoerce } from '@/test-utils/unsafe-coerce';
import { WorkspaceCreationService, type WorkspaceCreationSource } from './creation.service';

type Logger = ReturnType<typeof createLogger>;

// Mock dependencies
vi.mock('@/backend/services/workspace/resources/project.accessor');
vi.mock('@/backend/services/workspace/resources/workspace.accessor');
vi.mock('@/backend/services/settings');
vi.mock('@/backend/services/git-ops.service');
vi.mock('@/backend/services/workspace/service/worktree/worktree-lifecycle.service');

describe('WorkspaceCreationService', () => {
  let service: WorkspaceCreationService;
  let mockLogger: Logger;

  const mockWorkspace: Workspace = {
    id: 'ws-123',
    projectId: 'proj-1',
    name: 'Test Workspace',
    description: null,
    status: 'NEW',
    branchName: null,
    worktreePath: null,
    isAutoGeneratedBranch: false,
    creationSource: 'MANUAL',
    creationMetadata: null,
    prUrl: null,
    githubIssueNumber: null,
    githubIssueUrl: null,
    linearIssueId: null,
    linearIssueIdentifier: null,
    linearIssueUrl: null,
    defaultSessionProvider: 'WORKSPACE_DEFAULT',
    ratchetSessionProvider: 'WORKSPACE_DEFAULT',
    prNumber: null,
    prState: 'NONE',
    prReviewState: null,
    prCiStatus: 'UNKNOWN',
    prUpdatedAt: null,
    prCiFailedAt: null,
    prCiLastNotifiedAt: null,
    prReviewLastCheckedAt: null,
    prReviewLastCommentId: null,
    ratchetEnabled: true,
    ratchetState: 'IDLE',
    ratchetLastCheckedAt: null,
    ratchetActiveSessionId: null,
    ratchetLastCiRunId: null,
    hasHadSessions: false,
    cachedKanbanColumn: 'WAITING',
    stateComputedAt: null,
    initErrorMessage: null,
    initOutput: null,
    initStartedAt: null,
    initCompletedAt: null,
    initRetryCount: 0,
    runScriptCommand: null,
    runScriptPostRunCommand: null,
    runScriptCleanupCommand: null,
    runScriptPid: null,
    runScriptPort: null,
    runScriptStartedAt: null,
    runScriptStatus: 'IDLE',
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  const mockProject = {
    id: 'proj-1',
    name: 'Test Project',
    slug: 'test-project',
    repoPath: '/path/to/repo',
    worktreeBasePath: '/path/to/worktrees',
    defaultBranch: 'main',
    githubOwner: null,
    githubRepo: null,
    issueProvider: 'GITHUB' as const,
    issueTrackerConfig: null,
    isArchived: false,
    startupScriptCommand: null,
    startupScriptPath: null,
    startupScriptTimeout: 300,
    createdAt: new Date(),
    updatedAt: new Date(),
    workspaces: [],
  };

  beforeEach(() => {
    vi.clearAllMocks();

    mockLogger = unsafeCoerce<Logger>({
      info: vi.fn(),
      warn: vi.fn(),
      error: vi.fn(),
      debug: vi.fn(),
    });

    service = new WorkspaceCreationService({
      logger: mockLogger,
    });

    // Default mocks
    const mockUserSettings: UserSettings = {
      id: '1',
      userId: 'default',
      preferredIde: 'cursor',
      customIdeCommand: '',
      playSoundOnComplete: true,
      notificationSoundPath: null,
      workspaceOrder: null,
      cachedSlashCommands: null,
      ratchetEnabled: true,
      defaultSessionProvider: 'CLAUDE',
      defaultClaudeModel: 'sonnet',
      defaultCodexModel: 'default',
      defaultWorkspacePermissions: 'STRICT',
      ratchetPermissions: 'YOLO',
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    vi.spyOn(userSettingsAccessorModule.userSettingsAccessor, 'get').mockResolvedValue(
      mockUserSettings
    );
    vi.spyOn(workspaceAccessorModule.workspaceAccessor, 'create').mockResolvedValue(mockWorkspace);

    vi.spyOn(
      worktreeLifecycleServiceModule.worktreeLifecycleService,
      'setInitMode'
    ).mockResolvedValue();
  });

  describe('create', () => {
    describe('MANUAL source', () => {
      it('should create workspace with manual source', async () => {
        const source: WorkspaceCreationSource = {
          type: 'MANUAL',
          projectId: 'proj-1',
          name: 'My Workspace',
          description: 'A test workspace',
          branchName: 'feature/test',
        };

        const result = await service.create(source);

        expect(result).toEqual(mockWorkspace);
        expect(workspaceAccessorModule.workspaceAccessor.create).toHaveBeenCalledWith({
          projectId: 'proj-1',
          name: 'My Workspace',
          description: 'A test workspace',
          branchName: 'feature/test',
          creationSource: 'MANUAL',
          ratchetEnabled: true,
        });
      });

      it('should use explicit ratchetEnabled value', async () => {
        const source: WorkspaceCreationSource = {
          type: 'MANUAL',
          projectId: 'proj-1',
          name: 'My Workspace',
          ratchetEnabled: false,
        };

        await service.create(source);

        expect(workspaceAccessorModule.workspaceAccessor.create).toHaveBeenCalledWith(
          expect.objectContaining({
            ratchetEnabled: false,
          })
        );
        // resolveWorkspaceCreationDefaults always reads user settings for ratchet defaults.
        expect(userSettingsAccessorModule.userSettingsAccessor.get).toHaveBeenCalled();
      });

      it('should default to user settings ratchetEnabled when not provided', async () => {
        const disabledSettings: UserSettings = {
          id: '1',
          userId: 'default',
          preferredIde: 'cursor',
          customIdeCommand: '',
          playSoundOnComplete: true,
          notificationSoundPath: null,
          workspaceOrder: null,
          cachedSlashCommands: null,
          ratchetEnabled: false,
          defaultSessionProvider: 'CLAUDE',
          defaultClaudeModel: 'sonnet',
          defaultCodexModel: 'default',
          defaultWorkspacePermissions: 'STRICT',
          ratchetPermissions: 'YOLO',
          createdAt: new Date(),
          updatedAt: new Date(),
        };
        vi.spyOn(userSettingsAccessorModule.userSettingsAccessor, 'get').mockResolvedValue(
          disabledSettings
        );

        const source: WorkspaceCreationSource = {
          type: 'MANUAL',
          projectId: 'proj-1',
          name: 'My Workspace',
        };

        await service.create(source);

        expect(workspaceAccessorModule.workspaceAccessor.create).toHaveBeenCalledWith(
          expect.objectContaining({
            ratchetEnabled: false,
          })
        );
      });

      it('fetches user settings once when ratchetEnabled is implicit', async () => {
        const source: WorkspaceCreationSource = {
          type: 'MANUAL',
          projectId: 'proj-1',
          name: 'My Workspace',
        };

        await service.create(source);

        expect(userSettingsAccessorModule.userSettingsAccessor.get).toHaveBeenCalledTimes(1);
      });

      it('persists initial prompt attachments in creation metadata', async () => {
        const source: WorkspaceCreationSource = {
          type: 'MANUAL',
          projectId: 'proj-1',
          name: 'My Workspace',
          initialPrompt: 'Review these files',
          initialAttachments: [
            {
              id: 'att-1',
              name: 'screenshot.png',
              type: 'image/png',
              size: 128,
              data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAAB',
              contentType: 'image',
            },
          ],
        };

        await service.create(source);

        expect(workspaceAccessorModule.workspaceAccessor.create).toHaveBeenCalledWith(
          expect.objectContaining({
            creationMetadata: {
              initialPrompt: 'Review these files',
              initialAttachments: source.initialAttachments,
            },
          })
        );
      });

      it('persists startup mode preset in creation metadata', async () => {
        const source: WorkspaceCreationSource = {
          type: 'MANUAL',
          projectId: 'proj-1',
          name: 'Planning Workspace',
          startupModePreset: 'plan',
        };

        await service.create(source);

        expect(workspaceAccessorModule.workspaceAccessor.create).toHaveBeenCalledWith(
          expect.objectContaining({
            creationMetadata: {
              startupModePreset: 'plan',
            },
          })
        );
      });
    });

    describe('RESUME_BRANCH source', () => {
      beforeEach(() => {
        vi.spyOn(projectAccessorModule.projectAccessor, 'findById').mockResolvedValue(mockProject);
        vi.spyOn(gitOpsServiceModule.gitOpsService, 'isBranchCheckedOut').mockResolvedValue(false);
      });

      it('should create workspace from resume branch source', async () => {
        const source: WorkspaceCreationSource = {
          type: 'RESUME_BRANCH',
          projectId: 'proj-1',
          branchName: 'existing-branch',
          name: 'Resumed Workspace',
        };

        const result = await service.create(source);

        expect(result).toEqual(mockWorkspace);
        expect(projectAccessorModule.projectAccessor.findById).toHaveBeenCalledWith('proj-1');
        expect(gitOpsServiceModule.gitOpsService.isBranchCheckedOut).toHaveBeenCalledWith(
          mockProject,
          'existing-branch'
        );
        expect(
          worktreeLifecycleServiceModule.worktreeLifecycleService.setInitMode
        ).toHaveBeenCalledWith('ws-123', true);
      });

      it('should use branch name as workspace name when name not provided', async () => {
        const source: WorkspaceCreationSource = {
          type: 'RESUME_BRANCH',
          projectId: 'proj-1',
          branchName: 'my-feature-branch',
        };

        await service.create(source);

        expect(workspaceAccessorModule.workspaceAccessor.create).toHaveBeenCalledWith(
          expect.objectContaining({
            name: 'my-feature-branch',
          })
        );
      });

      it('should throw error when project not found', async () => {
        vi.spyOn(projectAccessorModule.projectAccessor, 'findById').mockResolvedValue(null);

        const source: WorkspaceCreationSource = {
          type: 'RESUME_BRANCH',
          projectId: 'proj-1',
          branchName: 'existing-branch',
        };

        await expect(service.create(source)).rejects.toThrow('Project not found: proj-1');
      });

      it('should throw error when branch is already checked out', async () => {
        vi.spyOn(gitOpsServiceModule.gitOpsService, 'isBranchCheckedOut').mockResolvedValue(true);

        const source: WorkspaceCreationSource = {
          type: 'RESUME_BRANCH',
          projectId: 'proj-1',
          branchName: 'existing-branch',
        };

        await expect(service.create(source)).rejects.toThrow(
          "Branch 'existing-branch' is already checked out in another worktree."
        );
      });
    });

    describe('GITHUB_ISSUE source', () => {
      it('should create workspace from GitHub issue source', async () => {
        const source: WorkspaceCreationSource = {
          type: 'GITHUB_ISSUE',
          projectId: 'proj-1',
          issueNumber: 42,
          issueUrl: 'https://github.com/org/repo/issues/42',
          name: 'Fix bug #42',
        };

        const result = await service.create(source);

        expect(result).toEqual(mockWorkspace);
        expect(workspaceAccessorModule.workspaceAccessor.create).toHaveBeenCalledWith({
          projectId: 'proj-1',
          name: 'Fix bug #42',
          githubIssueNumber: 42,
          githubIssueUrl: 'https://github.com/org/repo/issues/42',
          creationSource: 'GITHUB_ISSUE',
          creationMetadata: {
            issueNumber: 42,
            issueUrl: 'https://github.com/org/repo/issues/42',
          },
          ratchetEnabled: true,
        });
      });

      it('should generate default name from issue number when name not provided', async () => {
        const source: WorkspaceCreationSource = {
          type: 'GITHUB_ISSUE',
          projectId: 'proj-1',
          issueNumber: 42,
          issueUrl: 'https://github.com/org/repo/issues/42',
        };

        await service.create(source);

        expect(workspaceAccessorModule.workspaceAccessor.create).toHaveBeenCalledWith(
          expect.objectContaining({
            name: 'Issue #42',
          })
        );
      });
    });

    describe('LINEAR_ISSUE source', () => {
      it('should create workspace from Linear issue source', async () => {
        const source: WorkspaceCreationSource = {
          type: 'LINEAR_ISSUE',
          projectId: 'proj-1',
          issueId: 'linear-uuid-123',
          issueIdentifier: 'ENG-42',
          issueUrl: 'https://linear.app/team/issue/ENG-42',
          name: 'Fix ENG-42',
        };

        const result = await service.create(source);

        expect(result).toEqual(mockWorkspace);
        expect(workspaceAccessorModule.workspaceAccessor.create).toHaveBeenCalledWith({
          projectId: 'proj-1',
          name: 'Fix ENG-42',
          linearIssueId: 'linear-uuid-123',
          linearIssueIdentifier: 'ENG-42',
          linearIssueUrl: 'https://linear.app/team/issue/ENG-42',
          creationSource: 'LINEAR_ISSUE',
          creationMetadata: {
            issueId: 'linear-uuid-123',
            issueIdentifier: 'ENG-42',
            issueUrl: 'https://linear.app/team/issue/ENG-42',
          },
          ratchetEnabled: true,
        });
      });

      it('should generate default name from issue identifier when name not provided', async () => {
        const source: WorkspaceCreationSource = {
          type: 'LINEAR_ISSUE',
          projectId: 'proj-1',
          issueId: 'linear-uuid-123',
          issueIdentifier: 'ENG-42',
          issueUrl: 'https://linear.app/team/issue/ENG-42',
        };

        await service.create(source);

        expect(workspaceAccessorModule.workspaceAccessor.create).toHaveBeenCalledWith(
          expect.objectContaining({
            name: 'ENG-42',
          })
        );
      });
    });
  });
});
