import type { Meta, StoryObj } from '@storybook/react';
import type { ComponentProps } from 'react';
import { fn } from 'storybook/test';
import { WorkspacesTableView } from './workspaces-table-view';

type WorkspaceRow = NonNullable<ComponentProps<typeof WorkspacesTableView>['workspaces']>[number];

const now = Date.now();

const baseWorkspace: WorkspaceRow = {
  id: 'ws-1',
  name: 'Refactor session hydration',
  description: 'Stabilize restore logic and retry flow',
  branchName: 'feature/session-hydration',
  isAutoGeneratedBranch: false,
  creationSource: 'MANUAL',
  creationMetadata: null,
  projectId: 'proj-1',
  worktreePath: '/tmp/workspaces/session-hydration',
  prUrl: 'https://github.com/example/repo/pull/42',
  prNumber: 42,
  defaultSessionProvider: 'WORKSPACE_DEFAULT',
  ratchetSessionProvider: 'WORKSPACE_DEFAULT',
  prState: 'OPEN',
  prReviewState: null,
  prCiStatus: 'SUCCESS',
  prUpdatedAt: null,
  prCiFailedAt: null,
  prCiLastNotifiedAt: null,
  prReviewLastCheckedAt: null,
  prReviewLastCommentId: null,
  status: 'READY',
  createdAt: new Date(now - 1000 * 60 * 60 * 12),
  updatedAt: new Date(now - 1000 * 60 * 30),
  initErrorMessage: null,
  initOutput: null,
  initStartedAt: null,
  initCompletedAt: null,
  initRetryCount: 0,
  githubIssueNumber: 101,
  githubIssueUrl: 'https://github.com/example/repo/issues/101',
  linearIssueId: null,
  linearIssueIdentifier: null,
  linearIssueUrl: null,
  hasHadSessions: true,
  cachedKanbanColumn: 'WORKING',
  stateComputedAt: new Date(now - 1000 * 60),
  runScriptCommand: null,
  runScriptCleanupCommand: null,
  runScriptPid: null,
  runScriptPort: null,
  runScriptStartedAt: null,
  runScriptStatus: 'IDLE',
  ratchetEnabled: true,
  ratchetState: 'READY',
  ratchetLastCheckedAt: null,
  ratchetActiveSessionId: null,
  ratchetLastCiRunId: null,
  agentSessions: [{ id: 's1' }, { id: 's2' }],
  pendingRequestType: null,
};

const workspaces: WorkspaceRow[] = [
  baseWorkspace,
  {
    ...baseWorkspace,
    id: 'ws-2',
    name: 'Fix CI retry loop',
    branchName: 'fix/ci-retry-loop',
    prNumber: 57,
    prUrl: 'https://github.com/example/repo/pull/57',
    prCiStatus: 'FAILURE',
    status: 'FAILED',
    initErrorMessage: 'Startup script exited with code 1',
    createdAt: new Date(now - 1000 * 60 * 60 * 24),
    pendingRequestType: 'permission_request',
    agentSessions: [{ id: 's3' }],
  },
  {
    ...baseWorkspace,
    id: 'ws-3',
    name: 'Investigate issue triage automation',
    branchName: 'chore/issue-triage',
    prState: 'NONE',
    prUrl: null,
    prNumber: null,
    prCiStatus: 'UNKNOWN',
    status: 'NEW',
    createdAt: new Date(now - 1000 * 60 * 60 * 48),
    pendingRequestType: 'user_question',
    agentSessions: [],
  },
];

const meta = {
  title: 'Pages/Workspaces/WorkspacesTableView',
  component: WorkspacesTableView,
  parameters: {
    layout: 'fullscreen',
  },
  tags: ['autodocs'],
  decorators: [
    (Story) => (
      <div className="min-h-screen bg-background">
        <Story />
      </div>
    ),
  ],
  args: {
    workspaces,
    isLoading: false,
    slug: 'example-project',
    statusFilter: 'all',
    viewMode: 'list',
    onStatusFilterChange: fn(),
    onViewModeChange: fn(),
    onResumeOpen: fn(),
    onCreateWorkspace: fn(),
    isCreatingWorkspace: false,
    resumeDialog: null,
  },
} satisfies Meta<typeof WorkspacesTableView>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Populated: Story = {};

export const Loading: Story = {
  args: {
    isLoading: true,
    workspaces: undefined,
  },
};

export const Empty: Story = {
  args: {
    workspaces: [],
  },
};

export const FailedOnlyFilter: Story = {
  args: {
    statusFilter: 'FAILED',
    workspaces: workspaces.filter((workspace) => workspace.status === 'FAILED'),
  },
};
