-- Split the run-script group off Workspace into its own 1:1 table.
--
-- Seven columns, two concerns, one row -- see the model docblock for why they
-- share it. Nothing here is derived, so the backfill copies all seven verbatim;
-- unlike the ratchet and PR splits there is no misnamed column to correct, only
-- the `runScript` prefix to drop now that the table name carries it.
--
-- `pid`/`port`/`startedAt` look like state a restart makes meaningless, and for
-- the process they describe they are. They are copied anyway because a SIGKILL
-- or crash orphans a run script -- it spawns with `detached: false`, so it
-- normally dies with the server -- and the pid is the only handle on the orphan.
-- Dropping these would leak one process per workspace that was running at the
-- moment of the upgrade.
--
-- `status` is copied for a narrower reason: STARTING and STOPPING are cleared at
-- the next startup by `resetStaleTransientStatuses` (it always was -- the column
-- moving does not change that), but RUNNING, COMPLETED and FAILED are not, and
-- they are what the kanban card and the sidebar read.

CREATE TABLE "WorkspaceRunScript" (
    "workspaceId" TEXT NOT NULL PRIMARY KEY,
    "command" TEXT,
    "postRunCommand" TEXT,
    "cleanupCommand" TEXT,
    "pid" INTEGER,
    "port" INTEGER,
    "startedAt" DATETIME,
    "status" TEXT NOT NULL DEFAULT 'IDLE',
    CONSTRAINT "WorkspaceRunScript_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Backfill one row per existing workspace before the columns go away. Every
-- workspace gets a row, including those that have never had a run script, so the
-- compare-and-swap on `status` always has a row to guard.
INSERT INTO "WorkspaceRunScript" ("workspaceId", "command", "postRunCommand", "cleanupCommand", "pid", "port", "startedAt", "status")
SELECT "id", "runScriptCommand", "runScriptPostRunCommand", "runScriptCleanupCommand", "runScriptPid", "runScriptPort", "runScriptStartedAt", "runScriptStatus"
FROM "Workspace";

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Workspace" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "worktreePath" TEXT,
    "branchName" TEXT,
    "isAutoGeneratedBranch" BOOLEAN NOT NULL DEFAULT false,
    "creationSource" TEXT NOT NULL DEFAULT 'MANUAL',
    "creationMetadata" JSONB,
    "initErrorMessage" TEXT,
    "initOutput" TEXT,
    "initStartedAt" DATETIME,
    "initCompletedAt" DATETIME,
    "initScriptPid" INTEGER,
    "initRetryCount" INTEGER NOT NULL DEFAULT 0,
    "githubIssueNumber" INTEGER,
    "githubIssueUrl" TEXT,
    "linearIssueId" TEXT,
    "linearIssueIdentifier" TEXT,
    "linearIssueUrl" TEXT,
    "defaultSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "ratchetSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "mode" TEXT NOT NULL DEFAULT 'STANDARD',
    "autoIterationStatus" TEXT,
    "autoIterationConfig" JSONB,
    "autoIterationProgress" JSONB,
    "autoIterationSessionId" TEXT,
    "periodicTaskId" TEXT,
    "parent_workspace_id" TEXT,
    "hasHadSessions" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "Workspace_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Workspace_periodicTaskId_fkey" FOREIGN KEY ("periodicTaskId") REFERENCES "PeriodicTask" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Workspace_parent_workspace_id_fkey" FOREIGN KEY ("parent_workspace_id") REFERENCES "Workspace" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Workspace" ("autoIterationConfig", "autoIterationProgress", "autoIterationSessionId", "autoIterationStatus", "branchName", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initScriptPid", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "mode", "name", "parent_workspace_id", "periodicTaskId", "projectId", "ratchetSessionProvider", "status", "updatedAt", "worktreePath") SELECT "autoIterationConfig", "autoIterationProgress", "autoIterationSessionId", "autoIterationStatus", "branchName", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initScriptPid", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "mode", "name", "parent_workspace_id", "periodicTaskId", "projectId", "ratchetSessionProvider", "status", "updatedAt", "worktreePath" FROM "Workspace";
DROP TABLE "Workspace";
ALTER TABLE "new_Workspace" RENAME TO "Workspace";
CREATE INDEX "Workspace_projectId_idx" ON "Workspace"("projectId");
CREATE INDEX "Workspace_status_idx" ON "Workspace"("status");
CREATE INDEX "Workspace_parent_workspace_id_idx" ON "Workspace"("parent_workspace_id");
CREATE INDEX "Workspace_projectId_status_idx" ON "Workspace"("projectId", "status");
CREATE INDEX "Workspace_projectId_updatedAt_idx" ON "Workspace"("projectId", "updatedAt");
CREATE INDEX "Workspace_projectId_createdAt_idx" ON "Workspace"("projectId", "createdAt");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- SQLite's RedefineTables above dropped and recreated "Workspace", which drops
-- every trigger attached to it. Recreate the depth-1 guards verbatim; any future
-- migration that redefines this table has to do the same.
CREATE TRIGGER enforce_workspace_depth_1
BEFORE INSERT ON "Workspace"
WHEN NEW."parent_workspace_id" IS NOT NULL
BEGIN
  -- Block self-parenting
  SELECT RAISE(ABORT, 'A workspace cannot be its own parent')
  WHERE NEW."id" = NEW."parent_workspace_id";
  -- Block grandchild chains: proposed parent must not already have a parent
  SELECT RAISE(ABORT, 'Child workspaces cannot have children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "id" = NEW."parent_workspace_id"
    AND "parent_workspace_id" IS NOT NULL
  );
END;

CREATE TRIGGER enforce_workspace_depth_1_update
BEFORE UPDATE ON "Workspace"
WHEN NEW."parent_workspace_id" IS NOT NULL
BEGIN
  -- Block self-parenting
  SELECT RAISE(ABORT, 'A workspace cannot be its own parent')
  WHERE NEW."id" = NEW."parent_workspace_id";
  -- Block grandchild chains: proposed parent must not already have a parent
  SELECT RAISE(ABORT, 'Child workspaces cannot have children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "id" = NEW."parent_workspace_id"
    AND "parent_workspace_id" IS NOT NULL
  );
  -- Block re-parenting a workspace that already has children
  SELECT RAISE(ABORT, 'Cannot re-parent a workspace that already has children (max depth 1)')
  WHERE EXISTS (
    SELECT 1 FROM "Workspace"
    WHERE "parent_workspace_id" = NEW."id"
  );
END;
