import type { Workspace, WorkspaceProviderSelection } from '@prisma-gen/client';
import { workspaceAccessor } from '@/backend/resource_accessors/workspace.accessor';
import type { WorkspaceStatus } from '@/shared/core';

class WorkspaceDataService {
  findById(id: string) {
    return workspaceAccessor.findById(id);
  }

  findByIdWithProject(id: string) {
    return workspaceAccessor.findByIdWithProject(id);
  }

  findByProjectId(
    projectId: string,
    filters?: { status?: WorkspaceStatus; limit?: number; offset?: number }
  ) {
    return workspaceAccessor.findByProjectId(projectId, filters);
  }

  findByIdsWithProject(ids: string[]) {
    return workspaceAccessor.findByIdsWithProject(ids);
  }

  setBranchName(id: string, branchName: string) {
    return workspaceAccessor.update(id, {
      branchName,
    });
  }

  clearAutoGeneratedBranch(id: string) {
    return workspaceAccessor.update(id, {
      isAutoGeneratedBranch: false,
    });
  }

  setWorkspaceName(id: string, name: string) {
    return workspaceAccessor.update(id, {
      name,
      isAutoGeneratedName: false,
    });
  }

  setRunScriptCommands(
    id: string,
    runScriptCommand: string | null,
    runScriptCleanupCommand: string | null
  ) {
    return workspaceAccessor.update(id, {
      runScriptCommand,
      runScriptCleanupCommand,
    });
  }

  update(
    id: string,
    data: {
      defaultSessionProvider?: WorkspaceProviderSelection;
      ratchetSessionProvider?: WorkspaceProviderSelection;
    }
  ) {
    return workspaceAccessor.update(id, {
      defaultSessionProvider: data.defaultSessionProvider,
      ratchetSessionProvider: data.ratchetSessionProvider,
    });
  }

  delete(id: string): Promise<Workspace> {
    return workspaceAccessor.delete(id);
  }
}

export const workspaceDataService = new WorkspaceDataService();
