import { describe, expect, it, vi } from 'vitest';

vi.mock('../prompts/branch-rename', () => ({
  buildBranchRenameInstruction: vi.fn(),
}));

vi.mock('../prompts/workflows', () => ({
  getWorkflowContent: vi.fn(),
}));

vi.mock('./logger.service', () => ({
  createLogger: () => ({
    debug: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
}));

import { buildBranchRenameInstruction } from '../prompts/branch-rename';
import { getWorkflowContent } from '../prompts/workflows';
import { SessionPromptBuilder } from './session.prompt-builder';

describe('SessionPromptBuilder', () => {
  it('injects branch rename instruction for auto-generated branches', () => {
    vi.mocked(getWorkflowContent).mockReturnValue('workflow');
    vi.mocked(buildBranchRenameInstruction).mockReturnValue('rename');

    const builder = new SessionPromptBuilder();
    const result = builder.buildSystemPrompt({
      workflow: 'default',
      workspace: {
        branchName: 'auto-branch',
        isAutoGeneratedBranch: true,
        name: 'Workspace A',
        description: 'desc',
      },
      project: { githubOwner: 'owner' },
    });

    expect(result.systemPrompt).toBe('renameworkflow');
    expect(result.workflowPrompt).toBe('workflow');
    expect(result.injectedBranchRename).toBe(true);
  });

  it('uses workflow prompt without branch rename when branch is not auto-generated', () => {
    vi.mocked(getWorkflowContent).mockReturnValue('workflow');

    const builder = new SessionPromptBuilder();
    const result = builder.buildSystemPrompt({
      workflow: 'default',
      workspace: {
        branchName: 'feature/real',
        isAutoGeneratedBranch: false,
        name: 'Workspace B',
        description: null,
      },
      project: { githubOwner: 'owner' },
    });

    expect(result.systemPrompt).toBe('workflow');
    expect(result.workflowPrompt).toBe('workflow');
    expect(result.injectedBranchRename).toBe(false);
  });

  it('returns undefined system prompt when workflow prompt is missing', () => {
    vi.mocked(getWorkflowContent).mockReturnValue(null);

    const builder = new SessionPromptBuilder();
    const result = builder.buildSystemPrompt({
      workflow: 'missing',
      workspace: {
        branchName: null,
        isAutoGeneratedBranch: false,
        name: 'Workspace C',
        description: null,
      },
      project: null,
    });

    expect(result.systemPrompt).toBeUndefined();
    expect(result.workflowPrompt).toBeUndefined();
    expect(result.injectedBranchRename).toBe(false);
  });

  it('does not inject branch rename when isAutoGeneratedBranch is undefined', () => {
    vi.mocked(getWorkflowContent).mockReturnValue('workflow');

    const builder = new SessionPromptBuilder();
    const result = builder.buildSystemPrompt({
      workflow: 'default',
      workspace: {
        branchName: 'some-branch',
        // isAutoGeneratedBranch not set (undefined)
        name: 'Workspace D',
        description: null,
      },
      project: { githubOwner: 'owner' },
    });

    expect(result.systemPrompt).toBe('workflow');
    expect(result.workflowPrompt).toBe('workflow');
    expect(result.injectedBranchRename).toBe(false);
  });
});
