import { isAutoGeneratedBranchName } from '../clients/git.client';
import { buildBranchRenameInstruction } from '../prompts/branch-rename';
import { getWorkflowContent } from '../prompts/workflows';

export type BuildPromptInput = {
  workflow: string;
  workspace: {
    branchName?: string | null;
    name: string;
    description?: string | null;
  };
  project?: { githubOwner?: string | null } | null;
};

export type BuildPromptResult = {
  workflowPrompt: string | undefined;
  systemPrompt: string | undefined;
  injectedBranchRename: boolean;
};

export class SessionPromptBuilder {
  shouldInjectBranchRename(workspace: { branchName?: string | null }): boolean {
    return !!workspace.branchName && isAutoGeneratedBranchName(workspace.branchName);
  }

  buildSystemPrompt({ workflow, workspace, project }: BuildPromptInput): BuildPromptResult {
    const workflowPrompt = getWorkflowContent(workflow) ?? undefined;
    let systemPrompt = workflowPrompt;
    let injectedBranchRename = false;

    if (this.shouldInjectBranchRename(workspace)) {
      const branchRenameInstruction = buildBranchRenameInstruction({
        branchPrefix: project?.githubOwner ?? '',
        workspaceName: workspace.name,
        workspaceDescription: workspace.description ?? undefined,
      });
      systemPrompt = branchRenameInstruction + (workflowPrompt ?? '');
      injectedBranchRename = true;
    }

    return { workflowPrompt, systemPrompt, injectedBranchRename };
  }
}

export const sessionPromptBuilder = new SessionPromptBuilder();
